In [1]:
import pandas as pd
df=pd.read_csv(r'C:\Users\Ipan98\Downloads\UCF_cc_chargeoff_2022.csv')
df

,MonthEndDate,SSN_id,SSNJoint_id,Account_id,MostRecentLinkedCard_id,CreditCard_id,CardType,CardNumberTransferDate,OpenDate,CreditLine,...,LifetimeDelinquent1CycleCount,LifetimeDelinquent2CycleCount,LifetimeDelinquent3CycleCount,LifetimeDelinquent4CycleCount,LifetimeDelinquent5CycleCount,LifetimeDelinquent6CycleCount,LifetimeDelinquent7CycleCount,ChargeOffDate,ChargeOffAmount,Target
0,2021-07-31,C4E52479-A99F-4D1F-89CA-A7E24565FEA0,NaN,EF24033A-BF83-4757-B8EB-892AA8653974,0F917AAB-C5A2-47E8-9822-5EF646436782,0F917AAB-C5A2-47E8-9822-5EF646436782,VISA PLATINUM,NaN,2019-08-21,18000.0,...,0,0,0,0,0,0,0,NaN,0.0,0
1,2021-06-30,C4E52479-A99F-4D1F-89CA-A7E24565FEA0,NaN,EF24033A-BF83-4757-B8EB-892AA8653974,0F917AAB-C5A2-47E8-9822-5EF646436782,0F917AAB-C5A2-47E8-9822-5EF646436782,VISA PLATINUM,NaN,2019-08-21,18000.0,...,0,0,0,0,0,0,0,NaN,0.0,0
2,2021-05-31,C4E52479-A99F-4D1F-89CA-A7E24565FEA0,NaN,EF24033A-BF83-4757-B8EB-892AA8653974,0F917AAB-C5A2-47E8-9822-5EF646436782,0F917AAB-C5A2-47E8-9822-5EF646436782,VISA PLATINUM,NaN,2019-08-21,18000.0,...,0,0,0,0,0,0,0,NaN,0.0,0
3,2021-04-30,C4E52479-A99F-4D1F-89CA-A7E24565FEA0,NaN,EF24033A-BF83-4757-B8EB-892AA8653974,0F917AAB-C5A2-47E8-9822-5EF646436782,0F917AAB-C5A2-47E8-9822-5EF646436782,VISA PLATINUM,NaN,2019-08-21,18000.0,...,0,0,0,0,0,0,0,NaN,0.0,0
4,2021-03-31,C4E52479-A99F-4D1F-89CA-A7E24565FEA0,NaN,EF24033A-BF83-4757-B8EB-892AA8653974,0F917AAB-C5A2-47E8-9822-5EF646436782,0F917AAB-C5A2-47E8-9822-5EF646436782,VISA PLATINUM,NaN,2019-08-21,18000.0,...,0,0,0,0,0,0,0,NaN,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1236968,2019-11-30,D0F4A0CE-70C9-48F6-BA3D-61CDC9C44984,NaN,ECE5BD95-37CF-4BF1-A27A-A4DFD24F16FF,38B526C1-619E-40F5-A212-7A202042751E,38B526C1-619E-40F5-A212-7A202042751E,VISA PREMIER CASH,2017-04-14,2016-11-30,14000.0,...,0,0,0,0,0,0,0,NaN,0.0,0
1236969,2019-10-31,D0F4A0CE-70C9-48F6-BA3D-61CDC9C44984,NaN,ECE5BD95-37CF-4BF1-A27A-A4DFD24F16FF,38B526C1-619E-40F5-A212-7A202042751E,38B526C1-619E-40F5-A212-7A202042751E,VISA PREMIER CASH,2017-04-14,2016-11-30,14000.0,...,0,0,0,0,0,0,0,NaN,0.0,0
1236970,2019-09-30,D0F4A0CE-70C9-48F6-BA3D-61CDC9C44984,NaN,ECE5BD95-37CF-4BF1-A27A-A4DFD24F16FF,38B526C1-619E-40F5-A212-7A202042751E,38B526C1-619E-40F5-A212-7A202042751E,VISA PREMIER CASH,2017-04-14,2016-11-30,10000.0,...,0,0,0,0,0,0,0,NaN,0.0,0
1236971,2019-08-31,D0F4A0CE-70C9-48F6-BA3D-61CDC9C44984,NaN,ECE5BD95-37CF-4BF1-A27A-A4DFD24F16FF,38B526C1-619E-40F5-A212-7A202042751E,38B526C1-619E-40F5-A212-7A202042751E,VISA PREMIER CASH,2017-04-14,2016-11-30,10000.0,...,0,0,0,0,0,0,0,NaN,0.0,0
1236972,2019-07-31,D0F4A0CE-70C9-48F6-BA3D-61CDC9C44984,NaN,ECE5BD95-37CF-4BF1-A27A-A4DFD24F16FF,38B526C1-619E-40F5-A212-7A202042751E,38B526C1-619E-40F5-A212-7A202042751E,VISA PREMIER CASH,2017-04-14,2016-11-30,10000.0,...,0,0,0,0,0,0,0,NaN,0.0,0

First let's begin by a quick inspection of our data fields

In [2]:
df.info(max_cols=37 ,show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1236973 entries, 0 to 1236972
Data columns (total 37 columns):
 #   Column                                Non-Null Count    Dtype
---  ------                                --------------    -----
 0   MonthEndDate                          1236973 non-null  object
 1   SSN_id                                1236973 non-null  object
 2   SSNJoint_id                           195084 non-null   object
 3   Account_id                            1236186 non-null  object
 4   MostRecentLinkedCard_id               1236973 non-null  object
 5   CreditCard_id                         1236973 non-null  object
 6   CardType                              1236973 non-null  object
 7   CardNumberTransferDate                756685 non-null   object
 8   OpenDate                              1236973 non-null  object
 9   CreditLine                            1236973 non-null  float64
 10  LastStatementDate                     1236973 non-null  object
 11  NextStatementDate                     1236967 non-null  object
 12  LastStatementBalanceAmount            1236973 non-null  float64
 13  LastStatementPurchaseAmount           1236973 non-null  float64
 14  LastStatementPurchaseReturnAmount     1236973 non-null  float64
 15  LastStatementMinimumPaymentDueAmount  1236973 non-null  float64
 16  NextPaymentDueDate                    1236973 non-null  object
 17  LastPaymentDate                       1236973 non-null  object
 18  PaymentEffectiveDate                  1236967 non-null  object
 19  LastStatementPaymentTotalAmount       1236973 non-null  float64
 20  CardExternalStatus                    1236973 non-null  object
 21  CardExternalStatusLastChangeDate      597637 non-null   object
 22  CardInternalStatus                    1236973 non-null  object
 23  ActivityHistory1_12                   1236973 non-null  object
 24  DelinquentDaysCount                   1236973 non-null  int64
 25  DelinquentDate                        841760 non-null   object
 26  DelinquentTotalAmount                 1236973 non-null  float64
 27  LifetimeDelinquent1CycleCount         1236973 non-null  int64
 28  LifetimeDelinquent2CycleCount         1236973 non-null  int64
 29  LifetimeDelinquent3CycleCount         1236973 non-null  int64
 30  LifetimeDelinquent4CycleCount         1236973 non-null  int64
 31  LifetimeDelinquent5CycleCount         1236973 non-null  int64
 32  LifetimeDelinquent6CycleCount         1236973 non-null  int64
 33  LifetimeDelinquent7CycleCount         1236973 non-null  int64
 34  ChargeOffDate                         223343 non-null   object
 35  ChargeOffAmount                       1236973 non-null  float64
 36  Target                                1236973 non-null  int64
dtypes: float64(8), int64(9), object(20)
memory usage: 349.2+ MB

In [3]:
df['CardExternalStatus'].unique()

array(['Active', 'Authorization Prohibited', 'Closed', 'Charged-Off',
       'Revoked', 'Lost', 'Bankrupt', 'Interest Prohibited', 'Stolen',
       'Frozen'], dtype=object)

One way to gather insight is to check the number of unique customer we have and how many entries they each have

In [4]:
len(df.CreditCard_id.unique())

63492

In [5]:
import numpy as np
np.mean(df.SSN_id.value_counts())

24.122879207457387

In [6]:
import numpy as np
from scipy import stats
stats.mode(df.CreditCard_id.value_counts())

C:\Users\Ipan98\AppData\Local\Temp\ipykernel_12948\3482907304.py:3: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(df.CreditCard_id.value_counts())

ModeResult(mode=array([25], dtype=int64), count=array([37699]))

In [7]:
from collections import Counter
Counter(df['Target'])

Counter({0: 1235853, 1: 1120})

In [8]:
df['Target'].value_counts()[1]

1120

In [9]:
len(df['CreditCard_id'][(df['Target']==1)].unique())

893

We can see that our dataset is imbalanced as of now, but before dealing with it let's look at the count of null in our dataset.

In [10]:
import plotly.express as px
nulls=df.isnull().sum()
fig=px.bar(x=nulls.index, y=nulls.values)
fig.show()

Let's look at the columns with the most nulls deeply and see what information they contains

In [11]:
df.columns

Index(['MonthEndDate', 'SSN_id', 'SSNJoint_id', 'Account_id',
       'MostRecentLinkedCard_id', 'CreditCard_id', 'CardType',
       'CardNumberTransferDate', 'OpenDate', 'CreditLine', 'LastStatementDate',
       'NextStatementDate', 'LastStatementBalanceAmount',
       'LastStatementPurchaseAmount', 'LastStatementPurchaseReturnAmount',
       'LastStatementMinimumPaymentDueAmount', 'NextPaymentDueDate',
       'LastPaymentDate', 'PaymentEffectiveDate',
       'LastStatementPaymentTotalAmount', 'CardExternalStatus',
       'CardExternalStatusLastChangeDate', 'CardInternalStatus',
       'ActivityHistory1_12', 'DelinquentDaysCount', 'DelinquentDate',
       'DelinquentTotalAmount', 'LifetimeDelinquent1CycleCount',
       'LifetimeDelinquent2CycleCount', 'LifetimeDelinquent3CycleCount',
       'LifetimeDelinquent4CycleCount', 'LifetimeDelinquent5CycleCount',
       'LifetimeDelinquent6CycleCount', 'LifetimeDelinquent7CycleCount',
       'ChargeOffDate', 'ChargeOffAmount', 'Target'],
      dtype='object')

In [28]:
df['CardInternalStatus'].unique()

array([0, 1, 2, 4, 3])

Some of the empty columns are going to be dropped as they contain too many missing informations, we are also going to drop other columns because the information contained might either be a source of leakage to our model predictions (CardExternalStatusChange), or they do not tell us enough (Account_id)

In [12]:
df=df.drop(columns=['SSN_id', 'SSNJoint_id', 'Account_id', 'OpenDate',
       'MostRecentLinkedCard_id', 'CardType','LastStatementDate',
       'NextStatementDate',
       'CardNumberTransferDate', 'CardExternalStatus', 'NextPaymentDueDate',
       'LastPaymentDate', 'PaymentEffectiveDate', 'DelinquentDate', 'ChargeOffDate', 'CardExternalStatusLastChangeDate', 'DelinquentDaysCount'])

Let's sort our dataframe by SSN_ID and the entry date

In [13]:
df=df.sort_values(['CreditCard_id','MonthEndDate' ],ascending=True)
df

,MonthEndDate,CreditCard_id,CreditLine,LastStatementBalanceAmount,LastStatementPurchaseAmount,LastStatementPurchaseReturnAmount,LastStatementMinimumPaymentDueAmount,LastStatementPaymentTotalAmount,CardInternalStatus,ActivityHistory1_12,DelinquentTotalAmount,LifetimeDelinquent1CycleCount,LifetimeDelinquent2CycleCount,LifetimeDelinquent3CycleCount,LifetimeDelinquent4CycleCount,LifetimeDelinquent5CycleCount,LifetimeDelinquent6CycleCount,LifetimeDelinquent7CycleCount,ChargeOffAmount,Target
1098701,2019-07-31,000160CC-F99B-4EE6-9E78-BAA722EAC4A5,27000.0,0.00,0.00,0.00,0.0,0.00,Active,ZIQQQ1QQZIAZ,0.0,14,0,0,0,0,0,0,0.0,0
1098700,2019-08-31,000160CC-F99B-4EE6-9E78-BAA722EAC4A5,27000.0,48.98,48.98,0.00,27.0,0.00,Active,AZIQQQ1QQZIA,0.0,14,0,0,0,0,0,0,0.0,0
1098699,2019-09-30,000160CC-F99B-4EE6-9E78-BAA722EAC4A5,27000.0,175.42,211.02,10.74,27.0,73.84,Active,QAZIQQQ1QQZI,0.0,14,0,0,0,0,0,0,0.0,0
1098698,2019-10-31,000160CC-F99B-4EE6-9E78-BAA722EAC4A5,27000.0,0.00,0.00,0.00,0.0,175.42,Active,IQAZIQQQ1QQZ,0.0,14,0,0,0,0,0,0,0.0,0
1098697,2019-11-30,000160CC-F99B-4EE6-9E78-BAA722EAC4A5,27000.0,0.00,0.00,0.00,0.0,0.00,Active,ZIQAZIQQQ1QQ,0.0,14,0,0,0,0,0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160191,2021-03-31,FFFF7BF3-BC1F-4F0E-9014-4A4C185D97C0,300.0,-0.31,0.00,0.00,0.0,37.03,Credit Balance,-I0IIJBQAII1,0.0,4,0,0,0,0,0,0,0.0,0
1160190,2021-04-30,FFFF7BF3-BC1F-4F0E-9014-4A4C185D97C0,300.0,0.00,0.00,0.00,0.0,0.00,Credit Balance,%-I0IIJBQAII,0.0,4,0,0,0,0,0,0,0.0,0
1160189,2021-05-31,FFFF7BF3-BC1F-4F0E-9014-4A4C185D97C0,300.0,-1.00,39.00,0.00,0.0,40.00,Credit Balance,#%-I0IIJBQAI,0.0,4,0,0,0,0,0,0,0.0,0
1160188,2021-06-30,FFFF7BF3-BC1F-4F0E-9014-4A4C185D97C0,300.0,-1.00,0.00,0.00,0.0,0.00,Active,%#%-I0IIJBQA,0.0,4,0,0,0,0,0,0,0.0,0
1160187,2021-07-31,FFFF7BF3-BC1F-4F0E-9014-4A4C185D97C0,300.0,165.78,206.78,0.00,29.0,40.00,Active,Q%#%-I0IIJBQ,0.0,4,0,0,0,0,0,0,0.0,0

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1236973 entries, 1098701 to 1160187
Data columns (total 20 columns):
 #   Column                                Non-Null Count    Dtype
---  ------                                --------------    -----
 0   MonthEndDate                          1236973 non-null  object
 1   CreditCard_id                         1236973 non-null  object
 2   CreditLine                            1236973 non-null  float64
 3   LastStatementBalanceAmount            1236973 non-null  float64
 4   LastStatementPurchaseAmount           1236973 non-null  float64
 5   LastStatementPurchaseReturnAmount     1236973 non-null  float64
 6   LastStatementMinimumPaymentDueAmount  1236973 non-null  float64
 7   LastStatementPaymentTotalAmount       1236973 non-null  float64
 8   CardInternalStatus                    1236973 non-null  object
 9   ActivityHistory1_12                   1236973 non-null  object
 10  DelinquentTotalAmount                 1236973 non-null  float64
 11  LifetimeDelinquent1CycleCount         1236973 non-null  int64
 12  LifetimeDelinquent2CycleCount         1236973 non-null  int64
 13  LifetimeDelinquent3CycleCount         1236973 non-null  int64
 14  LifetimeDelinquent4CycleCount         1236973 non-null  int64
 15  LifetimeDelinquent5CycleCount         1236973 non-null  int64
 16  LifetimeDelinquent6CycleCount         1236973 non-null  int64
 17  LifetimeDelinquent7CycleCount         1236973 non-null  int64
 18  ChargeOffAmount                       1236973 non-null  float64
 19  Target                                1236973 non-null  int64
dtypes: float64(8), int64(8), object(4)
memory usage: 198.2+ MB

We are left with 22 columns

In [15]:
df.columns

Index(['MonthEndDate', 'CreditCard_id', 'CreditLine',
       'LastStatementBalanceAmount', 'LastStatementPurchaseAmount',
       'LastStatementPurchaseReturnAmount',
       'LastStatementMinimumPaymentDueAmount',
       'LastStatementPaymentTotalAmount', 'CardInternalStatus',
       'ActivityHistory1_12', 'DelinquentTotalAmount',
       'LifetimeDelinquent1CycleCount', 'LifetimeDelinquent2CycleCount',
       'LifetimeDelinquent3CycleCount', 'LifetimeDelinquent4CycleCount',
       'LifetimeDelinquent5CycleCount', 'LifetimeDelinquent6CycleCount',
       'LifetimeDelinquent7CycleCount', 'ChargeOffAmount', 'Target'],
      dtype='object')

However, we still have multiple entry for each of our users while only having one finale state prediction (Delinquant or Not Delinquant). Our problem seems to be a time series classification. We are going to need to need to keep the last entry for each features, in addition for our numerical features we are going to generate new features which are correlated to the actual features such as the standard deviation, the minimum and maximum encountered such that our model can capture the different status of that customer account

In [16]:
features=[ 'CreditCard_id',  'CreditLine',
       'LastStatementBalanceAmount', 'LastStatementPurchaseAmount',
       'LastStatementPurchaseReturnAmount',
       'LastStatementMinimumPaymentDueAmount',
       'LastStatementPaymentTotalAmount',  'DelinquentTotalAmount',
       'LifetimeDelinquent1CycleCount', 'LifetimeDelinquent2CycleCount',
       'LifetimeDelinquent3CycleCount', 'LifetimeDelinquent4CycleCount',
       'LifetimeDelinquent5CycleCount', 'LifetimeDelinquent6CycleCount',
       'LifetimeDelinquent7CycleCount', 'ChargeOffAmount']
aggr=df[features].groupby("CreditCard_id").agg(['last', 'std', 'min', 'max'])
aggr.columns = ['_'.join(x) for x in aggr.columns]
aggr=aggr.reset_index()
aggr

,CreditCard_id,CreditLine_last,CreditLine_std,CreditLine_min,CreditLine_max,LastStatementBalanceAmount_last,LastStatementBalanceAmount_std,LastStatementBalanceAmount_min,LastStatementBalanceAmount_max,LastStatementPurchaseAmount_last,...,LifetimeDelinquent6CycleCount_min,LifetimeDelinquent6CycleCount_max,LifetimeDelinquent7CycleCount_last,LifetimeDelinquent7CycleCount_std,LifetimeDelinquent7CycleCount_min,LifetimeDelinquent7CycleCount_max,ChargeOffAmount_last,ChargeOffAmount_std,ChargeOffAmount_min,ChargeOffAmount_max
0,000160CC-F99B-4EE6-9E78-BAA722EAC4A5,27000.0,0.000000,27000.0,27000.0,0.00,471.821279,-505.00,1563.92,0.00,...,0,0,0,0.0,0,0,0.00,0.0,0.00,0.00
1,0001EB36-3038-45F5-8194-F0E9CC7AD4F3,5000.0,NaN,5000.0,5000.0,4519.51,NaN,4519.51,4519.51,186.32,...,0,0,0,NaN,0,0,0.00,NaN,0.00,0.00
2,00063A19-EC81-482A-8A53-629BD8D6E348,1000.0,0.000000,1000.0,1000.0,0.00,0.000000,0.00,0.00,0.00,...,1,1,3,0.0,3,3,1290.79,0.0,1290.79,1290.79
3,00065EE4-0433-4FFE-AA14-88A9802377EE,1000.0,0.000000,1000.0,1000.0,0.00,0.000000,0.00,0.00,0.00,...,1,1,3,0.0,3,3,952.46,0.0,952.46,952.46
4,0008153C-876D-415A-8258-86D0EE9DE263,500.0,0.000000,500.0,500.0,0.00,0.000000,0.00,0.00,0.00,...,0,0,0,0.0,0,0,0.00,0.0,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63487,FFFC311A-6E8B-42C7-B48D-963245F47BBC,2000.0,0.000000,2000.0,2000.0,0.00,153.684648,0.00,344.08,0.00,...,0,0,0,0.0,0,0,0.00,0.0,0.00,0.00
63488,FFFD7CCD-EB45-46E5-8500-1503F9C5267E,25500.0,0.000000,25500.0,25500.0,354.47,1899.272022,0.00,6729.28,0.00,...,0,0,0,0.0,0,0,0.00,0.0,0.00,0.00
63489,FFFDC3AB-5D2C-41F0-9CCA-696F745DCC09,12500.0,1150.447483,9500.0,12500.0,3017.17,2370.266858,0.00,5510.13,1437.15,...,0,0,0,0.0,0,0,0.00,0.0,0.00,0.00
63490,FFFE5736-45D4-4157-A5BD-C8AAF6C54FB3,12500.0,0.000000,12500.0,12500.0,20.88,1426.365113,13.99,4821.00,20.88,...,0,0,0,0.0,0,0,0.00,0.0,0.00,0.00
63491,FFFF7BF3-BC1F-4F0E-9014-4A4C185D97C0,300.0,0.000000,300.0,300.0,165.78,111.041627,-1.00,334.47,206.78,...,0,0,0,0.0,0,0,0.00,0.0,0.00,0.00

For the categorical values, we will get the last entry and the mode also known as the most common values

In [18]:
from sklearn.preprocessing import LabelEncoder
df['CardInternalStatus']= LabelEncoder().fit_transform(df['CardInternalStatus'])
df['ActivityHistory1_12']= LabelEncoder().fit_transform(df['ActivityHistory1_12'])
cat=['CreditCard_id', 'CardInternalStatus',
       'ActivityHistory1_12', 'Target']
aggr_cat=df[cat].groupby("CreditCard_id").agg(['last',lambda x: pd.Series.mode(x)[0]])#lambda x: pd.Series.mode(x)[0]
aggr_cat.columns = ['_'.join(x) for x in aggr_cat.columns]
aggr_cat=aggr_cat.reset_index()
aggr_cat=aggr_cat.drop(columns=['Target_<lambda_0>'])
aggr_cat.columns=['CreditCard_id', 'CardInternalStatus_last',
       'CardInternalStatus_mode', 'ActivityHistory1_12_last',
       'ActivityHistory1_12_mode', 'Target_last']
aggr_cat

,CreditCard_id,CardInternalStatus_last,CardInternalStatus_mode,ActivityHistory1_12_last,ActivityHistory1_12_mode,Target_last
0,000160CC-F99B-4EE6-9E78-BAA722EAC4A5,0,0,250095,1593,0
1,0001EB36-3038-45F5-8194-F0E9CC7AD4F3,0,0,185182,185182,0
2,00063A19-EC81-482A-8A53-629BD8D6E348,0,0,280877,280877,0
3,00065EE4-0433-4FFE-AA14-88A9802377EE,0,0,280877,280877,0
4,0008153C-876D-415A-8258-86D0EE9DE263,0,0,280877,280877,0
...,...,...,...,...,...,...
63487,FFFC311A-6E8B-42C7-B48D-963245F47BBC,0,0,95174,94700,0
63488,FFFD7CCD-EB45-46E5-8500-1503F9C5267E,0,0,98796,53074,0
63489,FFFDC3AB-5D2C-41F0-9CCA-696F745DCC09,0,0,215528,215528,0
63490,FFFE5736-45D4-4157-A5BD-C8AAF6C54FB3,0,0,215528,215528,0
63491,FFFF7BF3-BC1F-4F0E-9014-4A4C185D97C0,0,0,138645,524,0

In [19]:
len(df['CreditCard_id'][(df['Target']==1)].unique())

893

One thing we keep noticing is the change in the last 3 months before the last delinquancy entry, we should create features that should be able to capture that. We can do that by using the Exponential Moving Average(EMA) with the last 3 months entries. We are using the EMA as it applies more weight to later data

In [20]:
#SSN_id CreditCard_id
features=['CreditCard_id',  'CreditLine',
       'LastStatementBalanceAmount', 'LastStatementPurchaseAmount',
       'LastStatementPurchaseReturnAmount',
       'LastStatementMinimumPaymentDueAmount',
       'LastStatementPaymentTotalAmount', 'DelinquentTotalAmount',
       'LifetimeDelinquent1CycleCount', 'LifetimeDelinquent2CycleCount',
       'LifetimeDelinquent3CycleCount', 'LifetimeDelinquent4CycleCount',
       'LifetimeDelinquent5CycleCount', 'LifetimeDelinquent6CycleCount',
       'LifetimeDelinquent7CycleCount', 'ChargeOffAmount']
df_ema=df[features].groupby("CreditCard_id").ewm(span=3).mean()#24
df_ema=df_ema.reset_index()
df_ema=df_ema.drop(columns=['level_1'])
df_ema=df_ema.groupby("CreditCard_id").agg(['last'])
df_ema.columns = ['_ema_'.join(x) for x in df_ema.columns]
df_ema=df_ema.reset_index()
df_ema

,CreditCard_id,CreditLine_ema_last,LastStatementBalanceAmount_ema_last,LastStatementPurchaseAmount_ema_last,LastStatementPurchaseReturnAmount_ema_last,LastStatementMinimumPaymentDueAmount_ema_last,LastStatementPaymentTotalAmount_ema_last,DelinquentTotalAmount_ema_last,LifetimeDelinquent1CycleCount_ema_last,LifetimeDelinquent2CycleCount_ema_last,LifetimeDelinquent3CycleCount_ema_last,LifetimeDelinquent4CycleCount_ema_last,LifetimeDelinquent5CycleCount_ema_last,LifetimeDelinquent6CycleCount_ema_last,LifetimeDelinquent7CycleCount_ema_last,ChargeOffAmount_ema_last
0,000160CC-F99B-4EE6-9E78-BAA722EAC4A5,27000.000000,17.677647,21.137167,0.073243,0.634509,38.742111,0.000000,14.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.00
1,0001EB36-3038-45F5-8194-F0E9CC7AD4F3,5000.000000,4519.510000,186.320000,0.000000,136.000000,150.000000,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.00
2,00063A19-EC81-482A-8A53-629BD8D6E348,1000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.00000,2.0,1.0,1.0,1.0,1.0,3.0,1290.79
3,00065EE4-0433-4FFE-AA14-88A9802377EE,1000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.00000,1.0,1.0,1.0,1.0,1.0,3.0,952.46
4,0008153C-876D-415A-8258-86D0EE9DE263,500.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.00000,3.0,0.0,0.0,0.0,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63487,FFFC311A-6E8B-42C7-B48D-963245F47BBC,2000.000000,117.660000,0.000000,0.000000,9.333333,148.806667,0.000000,19.00000,7.0,3.0,1.0,0.0,0.0,0.0,0.00
63488,FFFD7CCD-EB45-46E5-8500-1503F9C5267E,25500.000000,794.569831,41.978301,73.670121,23.857562,415.300092,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.00
63489,FFFDC3AB-5D2C-41F0-9CCA-696F745DCC09,12499.919891,3895.929307,850.823711,0.000000,70.603314,1758.353550,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.00
63490,FFFE5736-45D4-4157-A5BD-C8AAF6C54FB3,12500.000000,344.482202,346.845862,0.002615,25.026563,670.445486,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.00
63491,FFFF7BF3-BC1F-4F0E-9014-4A4C185D97C0,300.000000,84.635936,108.295912,0.000000,15.276570,27.260117,0.039963,3.99852,0.0,0.0,0.0,0.0,0.0,0.0,0.00

After creating all those features, we can finally create our final dataFrame

In [21]:
df_merge = pd.merge(aggr, df_ema, how='outer', on=['CreditCard_id'])
df_merge = pd.merge(df_merge, aggr_cat, how='outer', on=['CreditCard_id'])
df_merge

,CreditCard_id,CreditLine_last,CreditLine_std,CreditLine_min,CreditLine_max,LastStatementBalanceAmount_last,LastStatementBalanceAmount_std,LastStatementBalanceAmount_min,LastStatementBalanceAmount_max,LastStatementPurchaseAmount_last,...,LifetimeDelinquent4CycleCount_ema_last,LifetimeDelinquent5CycleCount_ema_last,LifetimeDelinquent6CycleCount_ema_last,LifetimeDelinquent7CycleCount_ema_last,ChargeOffAmount_ema_last,CardInternalStatus_last,CardInternalStatus_mode,ActivityHistory1_12_last,ActivityHistory1_12_mode,Target_last
0,000160CC-F99B-4EE6-9E78-BAA722EAC4A5,27000.0,0.000000,27000.0,27000.0,0.00,471.821279,-505.00,1563.92,0.00,...,0.0,0.0,0.0,0.0,0.00,0,0,250095,1593,0
1,0001EB36-3038-45F5-8194-F0E9CC7AD4F3,5000.0,NaN,5000.0,5000.0,4519.51,NaN,4519.51,4519.51,186.32,...,0.0,0.0,0.0,0.0,0.00,0,0,185182,185182,0
2,00063A19-EC81-482A-8A53-629BD8D6E348,1000.0,0.000000,1000.0,1000.0,0.00,0.000000,0.00,0.00,0.00,...,1.0,1.0,1.0,3.0,1290.79,0,0,280877,280877,0
3,00065EE4-0433-4FFE-AA14-88A9802377EE,1000.0,0.000000,1000.0,1000.0,0.00,0.000000,0.00,0.00,0.00,...,1.0,1.0,1.0,3.0,952.46,0,0,280877,280877,0
4,0008153C-876D-415A-8258-86D0EE9DE263,500.0,0.000000,500.0,500.0,0.00,0.000000,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.00,0,0,280877,280877,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63487,FFFC311A-6E8B-42C7-B48D-963245F47BBC,2000.0,0.000000,2000.0,2000.0,0.00,153.684648,0.00,344.08,0.00,...,1.0,0.0,0.0,0.0,0.00,0,0,95174,94700,0
63488,FFFD7CCD-EB45-46E5-8500-1503F9C5267E,25500.0,0.000000,25500.0,25500.0,354.47,1899.272022,0.00,6729.28,0.00,...,0.0,0.0,0.0,0.0,0.00,0,0,98796,53074,0
63489,FFFDC3AB-5D2C-41F0-9CCA-696F745DCC09,12500.0,1150.447483,9500.0,12500.0,3017.17,2370.266858,0.00,5510.13,1437.15,...,0.0,0.0,0.0,0.0,0.00,0,0,215528,215528,0
63490,FFFE5736-45D4-4157-A5BD-C8AAF6C54FB3,12500.0,0.000000,12500.0,12500.0,20.88,1426.365113,13.99,4821.00,20.88,...,0.0,0.0,0.0,0.0,0.00,0,0,215528,215528,0
63491,FFFF7BF3-BC1F-4F0E-9014-4A4C185D97C0,300.0,0.000000,300.0,300.0,165.78,111.041627,-1.00,334.47,206.78,...,0.0,0.0,0.0,0.0,0.00,0,0,138645,524,0

Counting the distribution of our target between default and non default

We end up with 81 columns, and around 79 features, let's build a model. We are going to use Light GBM with a 0.03, using Dart tree, 10000 estimators, then 15000 estimators

In [22]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
search_params = { 
    'learning_rate' : 0.03, #0.065,
    #'lambda_l1': 8.481514197781607,
    'lambda_l2': 50, #0.0004266339834880936,
    'num_leaves': 100, #27,
    'feature_fraction': 0.19, #0.484, 0.3
    #'bagging_fraction': 0.8477112190030014,
    #'bagging_freq': 2,
    'min_child_samples': 2400 #40 #20
}

fixed_params={
    'objective': 'binary',
    'metric': 'custom', 
    'boosting_type' : 'dart',
    #'force_row_wise' : True,
    #'device': 'gpu',
    #'n_jobs': -1,
    #'extra_trees' : True,
    #'feature_pre_filter': False,
    'n_estimators': 15000, 
    'early_stopping_round': 100
}
import lightgbm as lgb
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,roc_auc_score
from lightgbm import LGBMClassifier, early_stopping, log_evaluation
y=df_merge['Target_last']
X=df_merge.iloc[:, 1:-1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
model = LGBMClassifier(**fixed_params, **search_params)
model.fit(X_train,y_train,eval_set=[(X_test,y_test),(X_train,y_train)],
          verbose=50,eval_metric='logloss', callbacks=[early_stopping(50), log_evaluation(0)])
predict=model.predict_proba(X_test)
predict = np.transpose([pred[1] for pred in predict])
print(roc_auc_score(y_test, predict))
y_pred=model.predict(X_test)
print(accuracy_score(y_test, y_pred))

C:\Users\Ipan98\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lightgbm\sklearn.py:736: UserWarning:

'verbose' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.

[LightGBM] [Warning] feature_fraction is set=0.19, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.19
[LightGBM] [Warning] lambda_l2 is set=50, reg_lambda=0.0 will be ignored. Current value: lambda_l2=50

C:\Users\Ipan98\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lightgbm\callback.py:223: UserWarning:

Early stopping is not available in dart mode

[50]	training's binary_logloss: 0.624116	valid_0's binary_logloss: 0.00270465
[100]	training's binary_logloss: 0.00960148	valid_0's binary_logloss: 0.00382211
[150]	training's binary_logloss: 0.00498957	valid_0's binary_logloss: 0.00409362
[200]	training's binary_logloss: 0.00364667	valid_0's binary_logloss: 0.00425701
[250]	training's binary_logloss: 0.00321152	valid_0's binary_logloss: 0.00427621
[300]	training's binary_logloss: 0.0030547	valid_0's binary_logloss: 0.00427634
[350]	training's binary_logloss: 0.00294963	valid_0's binary_logloss: 0.00425333
[400]	training's binary_logloss: 0.00288676	valid_0's binary_logloss: 0.00425245
[450]	training's binary_logloss: 0.00281404	valid_0's binary_logloss: 0.00421953
[500]	training's binary_logloss: 0.00273685	valid_0's binary_logloss: 0.0041852
[550]	training's binary_logloss: 0.00269228	valid_0's binary_logloss: 0.00416931
[600]	training's binary_logloss: 0.00263057	valid_0's binary_logloss: 0.00413584
[650]	training's binary_logloss: 0.00259006	valid_0's binary_logloss: 0.00411227
[700]	training's binary_logloss: 0.00251933	valid_0's binary_logloss: 0.00406161
[750]	training's binary_logloss: 0.00250897	valid_0's binary_logloss: 0.00407172
[800]	training's binary_logloss: 0.00246589	valid_0's binary_logloss: 0.00403938
[850]	training's binary_logloss: 0.00240524	valid_0's binary_logloss: 0.00400403
[900]	training's binary_logloss: 0.00234937	valid_0's binary_logloss: 0.00396038
[950]	training's binary_logloss: 0.00228272	valid_0's binary_logloss: 0.0039178
[1000]	training's binary_logloss: 0.00221045	valid_0's binary_logloss: 0.00386586
[1050]	training's binary_logloss: 0.00217146	valid_0's binary_logloss: 0.00383193
[1100]	training's binary_logloss: 0.00213347	valid_0's binary_logloss: 0.00380834
[1150]	training's binary_logloss: 0.00209721	valid_0's binary_logloss: 0.00378108
[1200]	training's binary_logloss: 0.00205504	valid_0's binary_logloss: 0.0037531
[1250]	training's binary_logloss: 0.0020201	valid_0's binary_logloss: 0.00372187
[1300]	training's binary_logloss: 0.0019498	valid_0's binary_logloss: 0.00367222
[1350]	training's binary_logloss: 0.00193054	valid_0's binary_logloss: 0.00365842
[1400]	training's binary_logloss: 0.00190074	valid_0's binary_logloss: 0.00363635
[1450]	training's binary_logloss: 0.00187652	valid_0's binary_logloss: 0.00362242
[1500]	training's binary_logloss: 0.00184736	valid_0's binary_logloss: 0.00360687
[1550]	training's binary_logloss: 0.0018082	valid_0's binary_logloss: 0.0035747
[1600]	training's binary_logloss: 0.00178687	valid_0's binary_logloss: 0.00356561
[1650]	training's binary_logloss: 0.00177562	valid_0's binary_logloss: 0.00355919
[1700]	training's binary_logloss: 0.00175762	valid_0's binary_logloss: 0.00354416
[1750]	training's binary_logloss: 0.00171621	valid_0's binary_logloss: 0.00351479
[1800]	training's binary_logloss: 0.00169636	valid_0's binary_logloss: 0.00350097
[1850]	training's binary_logloss: 0.00167252	valid_0's binary_logloss: 0.00348388
[1900]	training's binary_logloss: 0.00164232	valid_0's binary_logloss: 0.00346231
[1950]	training's binary_logloss: 0.00161774	valid_0's binary_logloss: 0.00344589
[2000]	training's binary_logloss: 0.00158721	valid_0's binary_logloss: 0.00342671
[2050]	training's binary_logloss: 0.00158229	valid_0's binary_logloss: 0.00342981
[2100]	training's binary_logloss: 0.00155706	valid_0's binary_logloss: 0.00341149
[2150]	training's binary_logloss: 0.00155336	valid_0's binary_logloss: 0.00342469
[2200]	training's binary_logloss: 0.00154342	valid_0's binary_logloss: 0.00341625
[2250]	training's binary_logloss: 0.0015317	valid_0's binary_logloss: 0.00340941
[2300]	training's binary_logloss: 0.0015083	valid_0's binary_logloss: 0.0033963
[2350]	training's binary_logloss: 0.00148028	valid_0's binary_logloss: 0.00338399
[2400]	training's binary_logloss: 0.0014696	valid_0's binary_logloss: 0.0033816
[2450]	training's binary_logloss: 0.00146827	valid_0's binary_logloss: 0.00339482
[2500]	training's binary_logloss: 0.00146346	valid_0's binary_logloss: 0.00339577
[2550]	training's binary_logloss: 0.00145073	valid_0's binary_logloss: 0.00339153
[2600]	training's binary_logloss: 0.00144523	valid_0's binary_logloss: 0.00339557
[2650]	training's binary_logloss: 0.00142559	valid_0's binary_logloss: 0.00337904
[2700]	training's binary_logloss: 0.00141388	valid_0's binary_logloss: 0.00337672
[2750]	training's binary_logloss: 0.00140575	valid_0's binary_logloss: 0.00337582
[2800]	training's binary_logloss: 0.0013921	valid_0's binary_logloss: 0.00337438
[2850]	training's binary_logloss: 0.00138285	valid_0's binary_logloss: 0.00337106
[2900]	training's binary_logloss: 0.00137388	valid_0's binary_logloss: 0.00336825
[2950]	training's binary_logloss: 0.00135353	valid_0's binary_logloss: 0.00335871
[3000]	training's binary_logloss: 0.00134433	valid_0's binary_logloss: 0.00336962
[3050]	training's binary_logloss: 0.00133023	valid_0's binary_logloss: 0.00336606
[3100]	training's binary_logloss: 0.00131697	valid_0's binary_logloss: 0.00335765
[3150]	training's binary_logloss: 0.00130267	valid_0's binary_logloss: 0.00335246
[3200]	training's binary_logloss: 0.00128991	valid_0's binary_logloss: 0.00334715
[3250]	training's binary_logloss: 0.0012882	valid_0's binary_logloss: 0.00335944
[3300]	training's binary_logloss: 0.0012797	valid_0's binary_logloss: 0.00335746
[3350]	training's binary_logloss: 0.00126587	valid_0's binary_logloss: 0.00334979
[3400]	training's binary_logloss: 0.00126293	valid_0's binary_logloss: 0.00335292
[3450]	training's binary_logloss: 0.00125448	valid_0's binary_logloss: 0.00335288
[3500]	training's binary_logloss: 0.00124542	valid_0's binary_logloss: 0.00334996
[3550]	training's binary_logloss: 0.00123929	valid_0's binary_logloss: 0.00335243
[3600]	training's binary_logloss: 0.00122849	valid_0's binary_logloss: 0.00334994
[3650]	training's binary_logloss: 0.00121711	valid_0's binary_logloss: 0.00335033
[3700]	training's binary_logloss: 0.00121216	valid_0's binary_logloss: 0.00335455
[3750]	training's binary_logloss: 0.00120204	valid_0's binary_logloss: 0.00335216
[3800]	training's binary_logloss: 0.00119334	valid_0's binary_logloss: 0.0033491
[3850]	training's binary_logloss: 0.00118453	valid_0's binary_logloss: 0.00334608
[3900]	training's binary_logloss: 0.00117206	valid_0's binary_logloss: 0.00334737
[3950]	training's binary_logloss: 0.00116586	valid_0's binary_logloss: 0.00335226
[4000]	training's binary_logloss: 0.00115309	valid_0's binary_logloss: 0.00334312
[4050]	training's binary_logloss: 0.00114402	valid_0's binary_logloss: 0.00334224
[4100]	training's binary_logloss: 0.0011369	valid_0's binary_logloss: 0.00334296
[4150]	training's binary_logloss: 0.00112707	valid_0's binary_logloss: 0.00334345
[4200]	training's binary_logloss: 0.00111724	valid_0's binary_logloss: 0.00334392
[4250]	training's binary_logloss: 0.00110763	valid_0's binary_logloss: 0.00334241
[4300]	training's binary_logloss: 0.00110134	valid_0's binary_logloss: 0.00334394
[4350]	training's binary_logloss: 0.00108937	valid_0's binary_logloss: 0.0033399
[4400]	training's binary_logloss: 0.00107964	valid_0's binary_logloss: 0.00334509
[4450]	training's binary_logloss: 0.00106797	valid_0's binary_logloss: 0.00334279
[4500]	training's binary_logloss: 0.00106309	valid_0's binary_logloss: 0.00334527
[4550]	training's binary_logloss: 0.00105283	valid_0's binary_logloss: 0.0033464
[4600]	training's binary_logloss: 0.00103886	valid_0's binary_logloss: 0.003342
[4650]	training's binary_logloss: 0.0010327	valid_0's binary_logloss: 0.00334529
[4700]	training's binary_logloss: 0.0010255	valid_0's binary_logloss: 0.00334776
[4750]	training's binary_logloss: 0.00101677	valid_0's binary_logloss: 0.00334674
[4800]	training's binary_logloss: 0.00100863	valid_0's binary_logloss: 0.00334554
[4850]	training's binary_logloss: 0.000997636	valid_0's binary_logloss: 0.0033435
[4900]	training's binary_logloss: 0.000989423	valid_0's binary_logloss: 0.00334416
[4950]	training's binary_logloss: 0.00098415	valid_0's binary_logloss: 0.00334427
[5000]	training's binary_logloss: 0.000975726	valid_0's binary_logloss: 0.00334948
[5050]	training's binary_logloss: 0.00096292	valid_0's binary_logloss: 0.00334791
[5100]	training's binary_logloss: 0.000957482	valid_0's binary_logloss: 0.00335004
[5150]	training's binary_logloss: 0.000947873	valid_0's binary_logloss: 0.00334939
[5200]	training's binary_logloss: 0.000947708	valid_0's binary_logloss: 0.00335666
[5250]	training's binary_logloss: 0.000941178	valid_0's binary_logloss: 0.00335415
[5300]	training's binary_logloss: 0.000937174	valid_0's binary_logloss: 0.00335498
[5350]	training's binary_logloss: 0.000931116	valid_0's binary_logloss: 0.00335207
[5400]	training's binary_logloss: 0.000923975	valid_0's binary_logloss: 0.00335048
[5450]	training's binary_logloss: 0.000917512	valid_0's binary_logloss: 0.00334995
[5500]	training's binary_logloss: 0.000914498	valid_0's binary_logloss: 0.003351
[5550]	training's binary_logloss: 0.000906757	valid_0's binary_logloss: 0.00334594
[5600]	training's binary_logloss: 0.00090219	valid_0's binary_logloss: 0.00334746
[5650]	training's binary_logloss: 0.000898548	valid_0's binary_logloss: 0.00334897
[5700]	training's binary_logloss: 0.000894857	valid_0's binary_logloss: 0.00335164
[5750]	training's binary_logloss: 0.00089303	valid_0's binary_logloss: 0.00335614
[5800]	training's binary_logloss: 0.00088937	valid_0's binary_logloss: 0.00335463
[5850]	training's binary_logloss: 0.00088201	valid_0's binary_logloss: 0.00335364
[5900]	training's binary_logloss: 0.000874749	valid_0's binary_logloss: 0.00335094
[5950]	training's binary_logloss: 0.000870426	valid_0's binary_logloss: 0.00335075
[6000]	training's binary_logloss: 0.000865683	valid_0's binary_logloss: 0.00334914
[6050]	training's binary_logloss: 0.00086255	valid_0's binary_logloss: 0.00335037
[6100]	training's binary_logloss: 0.000858902	valid_0's binary_logloss: 0.00335202
[6150]	training's binary_logloss: 0.000855407	valid_0's binary_logloss: 0.00335712
[6200]	training's binary_logloss: 0.00085181	valid_0's binary_logloss: 0.00335418
[6250]	training's binary_logloss: 0.000848603	valid_0's binary_logloss: 0.00335546
[6300]	training's binary_logloss: 0.000844614	valid_0's binary_logloss: 0.00335546
[6350]	training's binary_logloss: 0.000837836	valid_0's binary_logloss: 0.00335228
[6400]	training's binary_logloss: 0.00083101	valid_0's binary_logloss: 0.00335016
[6450]	training's binary_logloss: 0.00082615	valid_0's binary_logloss: 0.00335205
[6500]	training's binary_logloss: 0.000822701	valid_0's binary_logloss: 0.00335353
[6550]	training's binary_logloss: 0.000821019	valid_0's binary_logloss: 0.00335419
[6600]	training's binary_logloss: 0.000812451	valid_0's binary_logloss: 0.00334787
[6650]	training's binary_logloss: 0.000808652	valid_0's binary_logloss: 0.00335049
[6700]	training's binary_logloss: 0.000805605	valid_0's binary_logloss: 0.0033516
[6750]	training's binary_logloss: 0.000800516	valid_0's binary_logloss: 0.00335059
[6800]	training's binary_logloss: 0.000795905	valid_0's binary_logloss: 0.0033504
[6850]	training's binary_logloss: 0.000793642	valid_0's binary_logloss: 0.00335061
[6900]	training's binary_logloss: 0.000791336	valid_0's binary_logloss: 0.00335579
[6950]	training's binary_logloss: 0.000789087	valid_0's binary_logloss: 0.00335685
[7000]	training's binary_logloss: 0.000782381	valid_0's binary_logloss: 0.00335265
[7050]	training's binary_logloss: 0.000777337	valid_0's binary_logloss: 0.00335159
[7100]	training's binary_logloss: 0.000771015	valid_0's binary_logloss: 0.00335544
[7150]	training's binary_logloss: 0.000763246	valid_0's binary_logloss: 0.00335582
[7200]	training's binary_logloss: 0.000760176	valid_0's binary_logloss: 0.00335783
[7250]	training's binary_logloss: 0.000757146	valid_0's binary_logloss: 0.00336207
[7300]	training's binary_logloss: 0.000752544	valid_0's binary_logloss: 0.00336106
[7350]	training's binary_logloss: 0.000748535	valid_0's binary_logloss: 0.00336053
[7400]	training's binary_logloss: 0.000742609	valid_0's binary_logloss: 0.00336097
[7450]	training's binary_logloss: 0.000737645	valid_0's binary_logloss: 0.00336358
[7500]	training's binary_logloss: 0.000736398	valid_0's binary_logloss: 0.00336549
[7550]	training's binary_logloss: 0.000729602	valid_0's binary_logloss: 0.0033658
[7600]	training's binary_logloss: 0.000725897	valid_0's binary_logloss: 0.00336483
[7650]	training's binary_logloss: 0.000724252	valid_0's binary_logloss: 0.00336912
[7700]	training's binary_logloss: 0.000723457	valid_0's binary_logloss: 0.00337142
[7750]	training's binary_logloss: 0.000720136	valid_0's binary_logloss: 0.00337047
[7800]	training's binary_logloss: 0.00071583	valid_0's binary_logloss: 0.00337221
[7850]	training's binary_logloss: 0.000712323	valid_0's binary_logloss: 0.00336883
[7900]	training's binary_logloss: 0.0007087	valid_0's binary_logloss: 0.00336747
[7950]	training's binary_logloss: 0.000705796	valid_0's binary_logloss: 0.0033678
[8000]	training's binary_logloss: 0.000703798	valid_0's binary_logloss: 0.00337107
[8050]	training's binary_logloss: 0.000702846	valid_0's binary_logloss: 0.00337216
[8100]	training's binary_logloss: 0.000700072	valid_0's binary_logloss: 0.00337029
[8150]	training's binary_logloss: 0.000697096	valid_0's binary_logloss: 0.00337339
[8200]	training's binary_logloss: 0.000693101	valid_0's binary_logloss: 0.00337227
[8250]	training's binary_logloss: 0.000689892	valid_0's binary_logloss: 0.00337009
[8300]	training's binary_logloss: 0.000686478	valid_0's binary_logloss: 0.00337111
[8350]	training's binary_logloss: 0.000683467	valid_0's binary_logloss: 0.00337204
[8400]	training's binary_logloss: 0.000681096	valid_0's binary_logloss: 0.00337171
[8450]	training's binary_logloss: 0.000678673	valid_0's binary_logloss: 0.00337331
[8500]	training's binary_logloss: 0.000676458	valid_0's binary_logloss: 0.00337603
[8550]	training's binary_logloss: 0.000676036	valid_0's binary_logloss: 0.00338026
[8600]	training's binary_logloss: 0.000674067	valid_0's binary_logloss: 0.00337789
[8650]	training's binary_logloss: 0.000670585	valid_0's binary_logloss: 0.00337636
[8700]	training's binary_logloss: 0.000664953	valid_0's binary_logloss: 0.00337427
[8750]	training's binary_logloss: 0.000660478	valid_0's binary_logloss: 0.00337534
[8800]	training's binary_logloss: 0.00065526	valid_0's binary_logloss: 0.00337873
[8850]	training's binary_logloss: 0.000650292	valid_0's binary_logloss: 0.0033807
[8900]	training's binary_logloss: 0.000648319	valid_0's binary_logloss: 0.00338247
[8950]	training's binary_logloss: 0.000646632	valid_0's binary_logloss: 0.00338454
[9000]	training's binary_logloss: 0.000644188	valid_0's binary_logloss: 0.00338343
[9050]	training's binary_logloss: 0.000642012	valid_0's binary_logloss: 0.00338616
[9100]	training's binary_logloss: 0.000638934	valid_0's binary_logloss: 0.00338535
[9150]	training's binary_logloss: 0.000634149	valid_0's binary_logloss: 0.00338706
[9200]	training's binary_logloss: 0.000630667	valid_0's binary_logloss: 0.00338702
[9250]	training's binary_logloss: 0.000627604	valid_0's binary_logloss: 0.00338698
[9300]	training's binary_logloss: 0.000622454	valid_0's binary_logloss: 0.00338824
[9350]	training's binary_logloss: 0.00061982	valid_0's binary_logloss: 0.00338849
[9400]	training's binary_logloss: 0.000616794	valid_0's binary_logloss: 0.0033898
[9450]	training's binary_logloss: 0.000612621	valid_0's binary_logloss: 0.00339242
[9500]	training's binary_logloss: 0.000611208	valid_0's binary_logloss: 0.00339642
[9550]	training's binary_logloss: 0.000609818	valid_0's binary_logloss: 0.00339639
[9600]	training's binary_logloss: 0.000607219	valid_0's binary_logloss: 0.00339656
[9650]	training's binary_logloss: 0.000606244	valid_0's binary_logloss: 0.0033998
[9700]	training's binary_logloss: 0.000604485	valid_0's binary_logloss: 0.00339823
[9750]	training's binary_logloss: 0.000601223	valid_0's binary_logloss: 0.00339744
[9800]	training's binary_logloss: 0.000599223	valid_0's binary_logloss: 0.00339863
[9850]	training's binary_logloss: 0.000596233	valid_0's binary_logloss: 0.00339823
[9900]	training's binary_logloss: 0.000595091	valid_0's binary_logloss: 0.00339912
[9950]	training's binary_logloss: 0.000592576	valid_0's binary_logloss: 0.00339916
[10000]	training's binary_logloss: 0.000590099	valid_0's binary_logloss: 0.00339919
[10050]	training's binary_logloss: 0.00058655	valid_0's binary_logloss: 0.00339987
[10100]	training's binary_logloss: 0.000584733	valid_0's binary_logloss: 0.00340354
[10150]	training's binary_logloss: 0.000583072	valid_0's binary_logloss: 0.0034047
[10200]	training's binary_logloss: 0.000579723	valid_0's binary_logloss: 0.00340234
[10250]	training's binary_logloss: 0.000578362	valid_0's binary_logloss: 0.0034053
[10300]	training's binary_logloss: 0.000576234	valid_0's binary_logloss: 0.0034029
[10350]	training's binary_logloss: 0.000571615	valid_0's binary_logloss: 0.00340249
[10400]	training's binary_logloss: 0.000568645	valid_0's binary_logloss: 0.00340395
[10450]	training's binary_logloss: 0.000567716	valid_0's binary_logloss: 0.00340658
[10500]	training's binary_logloss: 0.000565572	valid_0's binary_logloss: 0.00340442
[10550]	training's binary_logloss: 0.000563268	valid_0's binary_logloss: 0.00340595
[10600]	training's binary_logloss: 0.000560855	valid_0's binary_logloss: 0.00340649
[10650]	training's binary_logloss: 0.000557705	valid_0's binary_logloss: 0.00340784
[10700]	training's binary_logloss: 0.000554875	valid_0's binary_logloss: 0.00340834
[10750]	training's binary_logloss: 0.000551735	valid_0's binary_logloss: 0.00340906
[10800]	training's binary_logloss: 0.000548065	valid_0's binary_logloss: 0.00341015
[10850]	training's binary_logloss: 0.000543551	valid_0's binary_logloss: 0.00341206
[10900]	training's binary_logloss: 0.000542833	valid_0's binary_logloss: 0.00341518
[10950]	training's binary_logloss: 0.000541229	valid_0's binary_logloss: 0.0034168
[11000]	training's binary_logloss: 0.000540486	valid_0's binary_logloss: 0.00341666
[11050]	training's binary_logloss: 0.000538748	valid_0's binary_logloss: 0.00341737
[11100]	training's binary_logloss: 0.000537862	valid_0's binary_logloss: 0.0034192
[11150]	training's binary_logloss: 0.000537074	valid_0's binary_logloss: 0.00341966
[11200]	training's binary_logloss: 0.000534306	valid_0's binary_logloss: 0.00341948
[11250]	training's binary_logloss: 0.000534416	valid_0's binary_logloss: 0.00342117
[11300]	training's binary_logloss: 0.000533553	valid_0's binary_logloss: 0.00342359
[11350]	training's binary_logloss: 0.000532076	valid_0's binary_logloss: 0.0034248
[11400]	training's binary_logloss: 0.000529228	valid_0's binary_logloss: 0.00342105
[11450]	training's binary_logloss: 0.000528001	valid_0's binary_logloss: 0.00341965
[11500]	training's binary_logloss: 0.0005246	valid_0's binary_logloss: 0.00341789
[11550]	training's binary_logloss: 0.000522102	valid_0's binary_logloss: 0.00341698
[11600]	training's binary_logloss: 0.000519867	valid_0's binary_logloss: 0.00342095
[11650]	training's binary_logloss: 0.000517879	valid_0's binary_logloss: 0.00342109
[11700]	training's binary_logloss: 0.000514589	valid_0's binary_logloss: 0.00342191
[11750]	training's binary_logloss: 0.000511865	valid_0's binary_logloss: 0.00342071
[11800]	training's binary_logloss: 0.000508815	valid_0's binary_logloss: 0.00342438
[11850]	training's binary_logloss: 0.00050487	valid_0's binary_logloss: 0.00342629
[11900]	training's binary_logloss: 0.000503121	valid_0's binary_logloss: 0.00342863
[11950]	training's binary_logloss: 0.000501763	valid_0's binary_logloss: 0.00342815
[12000]	training's binary_logloss: 0.000498892	valid_0's binary_logloss: 0.00342734
[12050]	training's binary_logloss: 0.000496992	valid_0's binary_logloss: 0.00342889
[12100]	training's binary_logloss: 0.000497417	valid_0's binary_logloss: 0.00343047

In [30]:
import plotly.figure_factory as ff
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score,confusion_matrix,roc_auc_score
fig = ff.create_annotated_heatmap(confusion_matrix(y_test, y_pred), x=['0','1'], y=['0','1'])
fig.show()

Trying Oversampling for Classification

In [31]:
from collections import Counter
from sklearn.model_selection import train_test_split
df_merge=df_merge.fillna(0)
y=df_merge['Target_last']
X=df_merge.iloc[:, 1:-1]
print(Counter(y))
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(sampling_strategy='minority')
X_ros, y_ros = ros.fit_resample(X_train, y_train)
# new class distribution 
print(Counter(y_ros))
from xgboost import XGBClassifier
import numpy as np
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score,confusion_matrix,roc_auc_score
clf=XGBClassifier()
clf.fit(X_ros, y_ros)
predict=clf.predict_proba(X_test)
predict = np.transpose([pred[1] for pred in predict])
print("ROC AUC: {}".format(roc_auc_score(y_test, predict, average=None)))

Counter({0: 63467, 1: 25})
Counter({0: 47599, 1: 47599})
ROC AUC: 0.9972397277539703

In [32]:
from sklearn.metrics import accuracy_score
prediction=clf.predict(X_test)
accuracy_score(prediction, y_test)

0.9994959994959995

In [33]:
import plotly.figure_factory as ff
fig = ff.create_annotated_heatmap(confusion_matrix(y_test, prediction), x=['0','1'], y=['0','1'])
fig.show()

In [ ]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 63492 entries, 0 to 63491
Data columns (total 81 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   CreditCard_id                                  63492 non-null  object
 1   CreditLine_last                                63492 non-null  float64
 2   CreditLine_std                                 63492 non-null  float64
 3   CreditLine_min                                 63492 non-null  float64
 4   CreditLine_max                                 63492 non-null  float64
 5   LastStatementBalanceAmount_last                63492 non-null  float64
 6   LastStatementBalanceAmount_std                 63492 non-null  float64
 7   LastStatementBalanceAmount_min                 63492 non-null  float64
 8   LastStatementBalanceAmount_max                 63492 non-null  float64
 9   LastStatementPurchaseAmount_last               63492 non-null  float64
 10  LastStatementPurchaseAmount_std                63492 non-null  float64
 11  LastStatementPurchaseAmount_min                63492 non-null  float64
 12  LastStatementPurchaseAmount_max                63492 non-null  float64
 13  LastStatementPurchaseReturnAmount_last         63492 non-null  float64
 14  LastStatementPurchaseReturnAmount_std          63492 non-null  float64
 15  LastStatementPurchaseReturnAmount_min          63492 non-null  float64
 16  LastStatementPurchaseReturnAmount_max          63492 non-null  float64
 17  LastStatementMinimumPaymentDueAmount_last      63492 non-null  float64
 18  LastStatementMinimumPaymentDueAmount_std       63492 non-null  float64
 19  LastStatementMinimumPaymentDueAmount_min       63492 non-null  float64
 20  LastStatementMinimumPaymentDueAmount_max       63492 non-null  float64
 21  LastStatementPaymentTotalAmount_last           63492 non-null  float64
 22  LastStatementPaymentTotalAmount_std            63492 non-null  float64
 23  LastStatementPaymentTotalAmount_min            63492 non-null  float64
 24  LastStatementPaymentTotalAmount_max            63492 non-null  float64
 25  DelinquentTotalAmount_last                     63492 non-null  float64
 26  DelinquentTotalAmount_std                      63492 non-null  float64
 27  DelinquentTotalAmount_min                      63492 non-null  float64
 28  DelinquentTotalAmount_max                      63492 non-null  float64
 29  LifetimeDelinquent1CycleCount_last             63492 non-null  int64
 30  LifetimeDelinquent1CycleCount_std              63492 non-null  float64
 31  LifetimeDelinquent1CycleCount_min              63492 non-null  int64
 32  LifetimeDelinquent1CycleCount_max              63492 non-null  int64
 33  LifetimeDelinquent2CycleCount_last             63492 non-null  int64
 34  LifetimeDelinquent2CycleCount_std              63492 non-null  float64
 35  LifetimeDelinquent2CycleCount_min              63492 non-null  int64
 36  LifetimeDelinquent2CycleCount_max              63492 non-null  int64
 37  LifetimeDelinquent3CycleCount_last             63492 non-null  int64
 38  LifetimeDelinquent3CycleCount_std              63492 non-null  float64
 39  LifetimeDelinquent3CycleCount_min              63492 non-null  int64
 40  LifetimeDelinquent3CycleCount_max              63492 non-null  int64
 41  LifetimeDelinquent4CycleCount_last             63492 non-null  int64
 42  LifetimeDelinquent4CycleCount_std              63492 non-null  float64
 43  LifetimeDelinquent4CycleCount_min              63492 non-null  int64
 44  LifetimeDelinquent4CycleCount_max              63492 non-null  int64
 45  LifetimeDelinquent5CycleCount_last             63492 non-null  int64
 46  LifetimeDelinquent5CycleCount_std              63492 non-null  float64
 47  LifetimeDelinquent5CycleCount_min              63492 non-null  int64
 48  LifetimeDelinquent5CycleCount_max              63492 non-null  int64
 49  LifetimeDelinquent6CycleCount_last             63492 non-null  int64
 50  LifetimeDelinquent6CycleCount_std              63492 non-null  float64
 51  LifetimeDelinquent6CycleCount_min              63492 non-null  int64
 52  LifetimeDelinquent6CycleCount_max              63492 non-null  int64
 53  LifetimeDelinquent7CycleCount_last             63492 non-null  int64
 54  LifetimeDelinquent7CycleCount_std              63492 non-null  float64
 55  LifetimeDelinquent7CycleCount_min              63492 non-null  int64
 56  LifetimeDelinquent7CycleCount_max              63492 non-null  int64
 57  ChargeOffAmount_last                           63492 non-null  float64
 58  ChargeOffAmount_std                            63492 non-null  float64
 59  ChargeOffAmount_min                            63492 non-null  float64
 60  ChargeOffAmount_max                            63492 non-null  float64
 61  CreditLine_ema_last                            63492 non-null  float64
 62  LastStatementBalanceAmount_ema_last            63492 non-null  float64
 63  LastStatementPurchaseAmount_ema_last           63492 non-null  float64
 64  LastStatementPurchaseReturnAmount_ema_last     63492 non-null  float64
 65  LastStatementMinimumPaymentDueAmount_ema_last  63492 non-null  float64
 66  LastStatementPaymentTotalAmount_ema_last       63492 non-null  float64
 67  DelinquentTotalAmount_ema_last                 63492 non-null  float64
 68  LifetimeDelinquent1CycleCount_ema_last         63492 non-null  float64
 69  LifetimeDelinquent2CycleCount_ema_last         63492 non-null  float64
 70  LifetimeDelinquent3CycleCount_ema_last         63492 non-null  float64
 71  LifetimeDelinquent4CycleCount_ema_last         63492 non-null  float64
 72  LifetimeDelinquent5CycleCount_ema_last         63492 non-null  float64
 73  LifetimeDelinquent6CycleCount_ema_last         63492 non-null  float64
 74  LifetimeDelinquent7CycleCount_ema_last         63492 non-null  float64
 75  ChargeOffAmount_ema_last                       63492 non-null  float64
 76  CardInternalStatus_last                        63492 non-null  int32
 77  CardInternalStatus_mode                        63492 non-null  int32
 78  ActivityHistory1_12_last                       63492 non-null  int32
 79  ActivityHistory1_12_mode                       63492 non-null  int32
 80  Target_last                                    63492 non-null  int64
dtypes: float64(54), int32(4), int64(22), object(1)
memory usage: 38.8+ MB

In [29]:
df_merge = pd.merge(aggr, df_ema, how='outer', on=['CreditCard_id'])
df_merge = pd.merge(df_merge, aggr_cat, how='outer', on=['CreditCard_id'])
df_merge

,CreditCard_id,CreditLine_last,CreditLine_std,CreditLine_min,CreditLine_max,LastStatementBalanceAmount_last,LastStatementBalanceAmount_std,LastStatementBalanceAmount_min,LastStatementBalanceAmount_max,LastStatementPurchaseAmount_last,...,LifetimeDelinquent4CycleCount_ema_last,LifetimeDelinquent5CycleCount_ema_last,LifetimeDelinquent6CycleCount_ema_last,LifetimeDelinquent7CycleCount_ema_last,ChargeOffAmount_ema_last,CardInternalStatus_last,CardInternalStatus_mode,ActivityHistory1_12_last,ActivityHistory1_12_mode,Target_last
0,000160CC-F99B-4EE6-9E78-BAA722EAC4A5,27000.0,0.000000,27000.0,27000.0,0.00,471.821279,-505.00,1563.92,0.00,...,0.0,0.0,0.0,0.0,0.00,0,0,250095,1593,0
1,0001EB36-3038-45F5-8194-F0E9CC7AD4F3,5000.0,NaN,5000.0,5000.0,4519.51,NaN,4519.51,4519.51,186.32,...,0.0,0.0,0.0,0.0,0.00,0,0,185182,185182,0
2,00063A19-EC81-482A-8A53-629BD8D6E348,1000.0,0.000000,1000.0,1000.0,0.00,0.000000,0.00,0.00,0.00,...,1.0,1.0,1.0,3.0,1290.79,0,0,280877,280877,0
3,00065EE4-0433-4FFE-AA14-88A9802377EE,1000.0,0.000000,1000.0,1000.0,0.00,0.000000,0.00,0.00,0.00,...,1.0,1.0,1.0,3.0,952.46,0,0,280877,280877,0
4,0008153C-876D-415A-8258-86D0EE9DE263,500.0,0.000000,500.0,500.0,0.00,0.000000,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.00,0,0,280877,280877,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63487,FFFC311A-6E8B-42C7-B48D-963245F47BBC,2000.0,0.000000,2000.0,2000.0,0.00,153.684648,0.00,344.08,0.00,...,1.0,0.0,0.0,0.0,0.00,0,0,95174,94700,0
63488,FFFD7CCD-EB45-46E5-8500-1503F9C5267E,25500.0,0.000000,25500.0,25500.0,354.47,1899.272022,0.00,6729.28,0.00,...,0.0,0.0,0.0,0.0,0.00,0,0,98796,53074,0
63489,FFFDC3AB-5D2C-41F0-9CCA-696F745DCC09,12500.0,1150.447483,9500.0,12500.0,3017.17,2370.266858,0.00,5510.13,1437.15,...,0.0,0.0,0.0,0.0,0.00,0,0,215528,215528,0
63490,FFFE5736-45D4-4157-A5BD-C8AAF6C54FB3,12500.0,0.000000,12500.0,12500.0,20.88,1426.365113,13.99,4821.00,20.88,...,0.0,0.0,0.0,0.0,0.00,0,0,215528,215528,0
63491,FFFF7BF3-BC1F-4F0E-9014-4A4C185D97C0,300.0,0.000000,300.0,300.0,165.78,111.041627,-1.00,334.47,206.78,...,0.0,0.0,0.0,0.0,0.00,0,0,138645,524,0

In [22]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
search_params = { 
    'learning_rate' : 0.005, #0.065,
    #'lambda_l1': 8.481514197781607,
    'lambda_l2': 50, #0.0004266339834880936,
    'num_leaves': 100, #27,
    'feature_fraction': 0.9, #0.484, 0.3
    #'bagging_fraction': 0.8477112190030014,
    #'bagging_freq': 2,
    'min_child_samples': 2400 #40 #20
}

fixed_params={
    'objective': 'regression',
    'metric': ['l1','l2'], 
    'boosting_type' : 'gbdt',
    #'force_row_wise' : True,
    #'device': 'gpu',
    #'n_jobs': -1,
    #'extra_trees' : True,
    #'feature_pre_filter': False,
    'n_estimators': 10000, 
    'early_stopping_round': 100
}
import lightgbm as lgb
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,roc_auc_score
from lightgbm import LGBMRegressor, early_stopping, log_evaluation
y=df_merge['DelinquentTotalAmount_last']
X=df_merge.drop(columns=['DelinquentTotalAmount_last', 'CreditCard_id', 'Target_last'])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)
model = LGBMRegressor(**fixed_params, **search_params)
model.fit(X_train,y_train,eval_set=[(X_test,y_test),(X_train,y_train)],
          verbose=50,eval_metric='l1', callbacks=[early_stopping(50), log_evaluation(0)])
#predict=model.predict_proba(X_test)
#predict = np.transpose([pred[1] for pred in predict])
#print(roc_auc_score(y_test, predict))
#y_pred=model.predict(X_test)
#accuracy_score(y_test, y_pred)

C:\Users\Ipan98\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lightgbm\sklearn.py:736: UserWarning:

'verbose' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.

[LightGBM] [Warning] feature_fraction is set=0.9, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9
[LightGBM] [Warning] lambda_l2 is set=50, reg_lambda=0.0 will be ignored. Current value: lambda_l2=50
Training until validation scores don't improve for 50 rounds
[50]	training's l1: 3.06489	training's l2: 535.363	valid_0's l1: 2.83981	valid_0's l2: 319.521
[100]	training's l1: 2.83242	training's l2: 517.014	valid_0's l1: 2.59955	valid_0's l2: 304.127
[150]	training's l1: 2.64915	training's l2: 503.636	valid_0's l1: 2.41077	valid_0's l2: 293.295
[200]	training's l1: 2.57167	training's l2: 493.117	valid_0's l1: 2.33508	valid_0's l2: 285.199
[250]	training's l1: 2.52596	training's l2: 484.201	valid_0's l1: 2.29506	valid_0's l2: 278.525
[300]	training's l1: 2.5076	training's l2: 476.526	valid_0's l1: 2.28132	valid_0's l2: 272.923
Early stopping, best iteration is:
[289]	training's l1: 2.50608	training's l2: 478.118	valid_0's l1: 2.27876	valid_0's l2: 274.07

LGBMRegressor(early_stopping_round=100, feature_fraction=0.9, lambda_l2=50,
              learning_rate=0.005, metric=['l1', 'l2'], min_child_samples=2400,
              n_estimators=10000, num_leaves=100, objective='regression')

In [24]:
feature_imp = pd.DataFrame(sorted(zip(model.feature_importances_,X.columns)), columns=['Value','Feature'])
feature_imp.tail(10)

    Value                                        Feature
68     75               LastStatementPurchaseAmount_last
69     84           LastStatementPurchaseAmount_ema_last
70     86  LastStatementMinimumPaymentDueAmount_ema_last
71    105                        CardInternalStatus_last
72    120                                 CreditLine_max
73    126      LastStatementMinimumPaymentDueAmount_last
74    133                      DelinquentTotalAmount_std
75    165                LastStatementBalanceAmount_last
76    228                       ActivityHistory1_12_last
77    237                 DelinquentTotalAmount_ema_last

In [25]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
y=df_merge['DelinquentTotalAmount_last']
X=df_merge.drop(columns=['DelinquentTotalAmount_last', 'CreditCard_id', 'Target_last'])
X=X.fillna(0)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)
reg = RandomForestRegressor()

reg.fit(X_train, y_train)#reg.fit(X, y)
reg.score(X_train, y_train)

0.996587582433569

In [26]:
from sklearn.metrics import mean_squared_error
y_pred=reg.predict(X_test)
print('The rmse of prediction is:', np.sqrt(mean_squared_error(y_test, y_pred)))

The rmse of prediction is: 5.8370851838628095

In [27]:
feature_imp = pd.DataFrame(sorted(zip(reg.feature_importances_,X.columns)), columns=['Value','Feature'])
feature_imp.tail(10)

       Value                                        Feature
68  0.001058                 LastStatementBalanceAmount_min
69  0.001322            LastStatementPaymentTotalAmount_max
70  0.001452            LastStatementBalanceAmount_ema_last
71  0.001467                       ActivityHistory1_12_last
72  0.001613                LastStatementBalanceAmount_last
73  0.002111  LastStatementMinimumPaymentDueAmount_ema_last
74  0.020716                      DelinquentTotalAmount_max
75  0.062466                        CardInternalStatus_last
76  0.147369      LastStatementMinimumPaymentDueAmount_last
77  0.742789                 DelinquentTotalAmount_ema_last

In [32]:
import plotly.express as px
import plotly.graph_objects as go
df=pd.DataFrame({'X_test':X_test.index, 'Predict':y_pred, 'Actual':y_test.values})
fig=px.scatter(df, x='X_test', y='Actual')
fig.add_trace(go.Scatter(x=df["X_test"], y=df["Predict"], name="Prediction",mode='markers', marker=dict(size=5,color='#000000',line=dict(width=2,color='#000000'))))
fig.show()

<h1>BackTesting</h1>

In [28]:
df[df['Target']==1].CreditCard_id.unique()

array(['00F567FC-053D-4AEF-B200-37B0ED41DF1A',
       '00FBF8D8-CF64-4983-BB0E-AEC67FF4420D',
       '0132FB64-26AA-4487-A3A9-050B808360E0',
       '01358069-8D5D-4216-92C3-F667AC785477',
       '0176A9F3-C014-4F81-A851-CFEB45995989',
       '01941913-7E20-45A5-9F74-059A634D8DC8',
       '026FDA86-3B45-48B3-B53B-2C6BFA63F0CE',
       '028FA58A-8C7A-4CD2-92E3-051112EBACED',
       '02B411DF-1BD3-4BE1-8FE4-F1BBCF584081',
       '02C9ACC4-B343-4E7D-B1DC-9FFA298DDE91',
       '0356B559-40CE-4E50-8298-E6058C0111D2',
       '03607E95-263D-4ECA-B1D6-A23A7508F9D5',
       '03E03940-1A1C-4941-8E27-2761DC0BE605',
       '049066BA-F6ED-4E77-9F1C-D095BAA12A1A',
       '0494D0CB-0A89-49A3-9BB1-6627B6FC011A',
       '049EB2AE-42A7-4BAF-A881-E88AD2CA8F21',
       '04CBEAB5-479A-4A86-AE53-3FA562490415',
       '04E08EA0-5DBB-4AD1-8C0F-5AFDB30F99DA',
       '0626E1C9-21AC-4539-9956-06A0C994D548',
       '06440B71-9C03-4D81-ABAD-AC1F4CC13D19',
       '06F6BEFA-1919-4EDC-82C8-78F636CAE84B',
       '07172130-B2FD-4B79-9495-C758012EC325',
       '0803D227-5A6D-4C29-8487-7FB492AB1941',
       '089EC2CB-7835-436C-8FDC-AD84BE5EBCCC',
       '09241904-1220-435A-9824-B56D2CD2E5C6',
       '0959021C-EA78-434E-BFD6-FB814E059924',
       '097943F3-0CC5-4907-A8ED-D6731E590BB1',
       '09B6A2AF-5F6F-4DE6-ABA4-253AB302031F',
       '0A53E551-46C2-49C3-B7F3-879391B42748',
       '0AFF7BFB-3EA2-4219-9C6C-0F6710AF58F6',
       '0B189988-F498-4AA1-BBA6-EBCFD9CDC3A3',
       '0B7602E3-F751-4DDB-97BD-1EEF62D5D7DA',
       '0BCEBF53-85E3-4BCB-84C3-D23411D3DBF5',
       '0CB01C71-3014-448E-A56F-D6DD837C7C84',
       '0CDE7C2A-05C9-4B03-BADE-9C7E0E20C457',
       '0D2ABDA5-F476-4120-98C1-4E09B88E35DD',
       '0D5207E9-181B-4641-BDB0-5BC1B6687092',
       '0D7A65F2-AA6C-4B03-AF1A-650E10E46C0D',
       '0D8CA015-DF75-4FC5-A8F0-A53ECF3C668B',
       '0DE754BF-6F12-4D58-B59F-AA2405D76E27',
       '0F2143D1-9B40-4F83-98C3-3A110779AD17',
       '0FC6A5D2-A265-41B6-A840-C90F42036E03',
       '0FCA6BC3-9AF1-4C18-8AE0-763ED76CB50B',
       '0FE63726-3B1F-43F3-8AEB-086F5F921151',
       '0FFF36B0-5672-431C-AB4F-43C9D67D4B17',
       '10A277C0-8955-420D-B07F-91FF61FDB6CE',
       '10CC1298-ABDF-4669-B7E5-BB3DA48F57EA',
       '113025B4-DC1F-4EB8-AA21-1813F9AC2D0A',
       '114C4475-6753-402A-9F3C-50691ED313E7',
       '115CDF11-C1E1-4903-9AF1-DCBDB34FAB3B',
       '11FE9630-5AB7-43E2-9152-DF0E4840DCEF',
       '1200ED17-3254-46A5-A7DD-360903703584',
       '123E29F9-D7AF-49A9-BB99-3E9BF94BCAF5',
       '12649D78-E58D-4AD2-9198-D18265780B6C',
       '12E155F8-44B2-40BD-8241-A3717F73CD25',
       '131A72E9-9831-4732-9B10-3760AC11A8AE',
       '13236CC7-87EA-49FA-BDDF-69EBB1087E48',
       '13B589D7-6A72-47F4-ACC9-F061339F6B79',
       '13F139CB-C755-43BF-A301-6E616C55D185',
       '14629C63-981F-4091-A7A8-D5F7073E5D8C',
       '147968CB-6D95-4459-8651-D92A462F561B',
       '148080E5-7B2F-455B-95F0-5F7C1A4AF5C2',
       '14C3C6AE-938C-4D4F-A182-91F0DB43D823',
       '150B6A99-8151-40CE-9EB7-F98BB58D670C',
       '15297BC9-12E9-4209-81B0-93ACD7D38D2D',
       '15E4B02D-05B8-49DC-8878-5D8CD066233D',
       '15FAAC9B-D849-433D-A9A0-37961956D791',
       '16343FDE-5EC3-461A-8931-43815D0F424A',
       '16439352-3AD3-4263-A1AB-3190AC8F6F10',
       '1645B5B9-5E59-46FD-A193-9F9C34F59C5B',
       '1667D481-59A4-4F8C-9376-A4E882D0EF1B',
       '16A4F16E-7032-42E0-B626-693B71FF791E',
       '16DA9A61-D5E5-47B2-8284-EA84CA17829E',
       '16F7AE0C-3CCE-4E8B-BB32-37F5C4D434AB',
       '173F8C48-A828-4405-8C91-C347E9A87916',
       '175C0860-4FD0-4A6C-956F-5E69E30AC8FE',
       '183220A7-F7B4-4E7E-B649-E7A9EE262967',
       '185E0A02-9875-4EF7-804B-FA39180B7DB0',
       '18924FAB-CD21-461C-AD97-86EA476ABC82',
       '1975B7EE-F482-445E-A03D-1CFD69552297',
       '1986F001-17C5-4864-9619-08EDEA3E85E6',
       '19DAA4EA-F94E-4B51-B25E-3D5B16B9EC7E',
       '1A134BE3-7866-4E7C-A7AF-EE9525C082FF',
       '1A554441-4CB3-4D8A-9753-5796C398071A',
       '1A6981C4-9D8D-45C1-875B-5D1B51B530B7',
       '1B03F621-5A8C-48EE-AA8B-67E0511204BB',
       '1B1CBB43-1C8C-4F0E-BE4D-433113C9695D',
       '1B411617-AFE3-491A-8590-BA3FE1967142',
       '1B4D78BE-5281-4950-BCEA-737701DF3382',
       '1B65FE78-1C3B-4718-88C0-ED6CF66B24A4',
       '1B926AFC-766E-4EDE-BB06-1011A9F29340',
       '1BA9762C-5045-4218-B6C5-1989A7E5CA73',
       '1C22F28D-5530-4B8D-8F8F-0D0BD0CACD0C',
       '1CE77253-9AAB-44FA-9511-8A4A875E488B',
       '1CF165F0-BC1F-4C70-9DFE-73918504B148',
       '1CFAB1AC-B20F-4425-A27B-439725DAA592',
       '1D0161F6-938B-460E-AE93-559B28C5C775',
       '1D190708-E74A-49D4-A562-6C2CD2B2E38A',
       '1DE5C71C-A1A0-4755-B92C-1EBC017451BD',
       '1E3161FD-63F6-4551-86C1-A882615C4BA9',
       '1EBC9BC2-D16B-4C5E-B027-8CF2E7B6A7A1',
       '1F04798E-118C-45A9-B925-46CDE4FD7EE3',
       '1F94BC78-464D-4A7C-ACCF-03DF2AC639DC',
       '1FFEA70A-6125-4275-AADD-CBEC03EA1B24',
       '2030DF8E-D846-44B4-BF62-B8E5F79D97EC',
       '206AF89E-6F97-4514-A064-C281A26FA685',
       '20DAB411-33CB-4854-AB5F-EF80900B5679',
       '20E69507-7644-45BF-AC22-8A99C01B30FD',
       '21461206-E898-449F-B667-A7C5DE87E74F',
       '21B93179-DFFA-49D3-AF55-A583ACDE67FD',
       '21C91D97-1586-4E33-90CF-C5AB0D944B5F',
       '21D0C02C-E194-4132-BA53-CD6D95BD0037',
       '221FB085-E81C-4E3C-8C59-AFB98E302BA5',
       '2274B018-A6E1-4ADB-9F4A-4D3238BED454',
       '22ABC223-7121-44D6-990B-2F50A0B1A3E5',
       '22BF51A9-51E8-423F-9FBF-DB017EF7238B',
       '22F7CE1D-237B-46BE-AEBF-89E1C743FA68',
       '23175695-0267-4871-A369-C95FA537CE21',
       '232F47B3-4E03-4AED-8CED-5CF3C94C1083',
       '2360F30F-2BAB-4D7C-9C95-67E5D4C78EEC',
       '236AD2A1-682B-4D43-9A67-C427965E83E7',
       '23CF6A79-CC78-4617-AB51-D0A955D37356',
       '2445FCA0-18DA-4D89-A719-29B5B19103D1',
       '24AAFB28-B552-4A5B-8277-D1B0E8D1840A',
       '2515E0B2-EEB8-4417-BCE0-0A1A656645DC',
       '25DD8586-43DF-400A-8F15-6D3DA9D06809',
       '26711A8C-B4AB-4437-8781-2819399995A4',
       '26E39C1E-4BEE-4987-914A-BF25F4C17B8A',
       '2723A80A-A8E0-408D-A31F-9E387C90497C',
       '27325B82-96DF-475F-9DA1-1DD639E31D27',
       '27E2465E-2518-4EAA-920E-034D926380CF',
       '285BAF9E-2FF6-46C5-9E86-33BA71426A8F',
       '2910080B-6E1F-4F52-BFDA-228C625A2598',
       '2936647E-B97D-47C8-B375-76FB802E7765',
       '2953E336-F156-46E8-AF19-5EAE422005D9',
       '29E4AC4D-CEE1-4C18-BE53-94FF9EB5D29E',
       '29E4E3EE-CC1E-493C-BF0D-B19031F602A0',
       '2ACE536C-7C75-4181-982B-F3D5FE8011FE',
       '2AF73862-6101-4DF7-B84F-96BFCCACEDC5',
       '2C393BF7-F2AD-49C9-8273-4B8CF85E5649',
       '2C6746B5-3E97-44DC-B6C9-F4F1D3CD6260',
       '2C71DC4F-2A64-4E36-942A-7F1C45A55C38',
       '2C748826-C150-4E6B-A49B-6F6E911E55BE',
       '2D264BEA-0A08-4A7C-BB7A-1D4A207969A4',
       '2D9BF9B3-4108-4EC5-B704-8C8D9A7F7D29',
       '2DD05015-221E-4132-9743-EC64968CB09E',
       '2E4192A5-D29A-4785-A795-9557DBD0F52F',
       '2E7296AD-5B7C-47D3-9CBF-57D6AF71BE78',
       '2EAECD2C-BC84-42DB-8431-228209F9BD28',
       '2EDD8048-DD80-4FB2-94C0-A8292C436184',
       '2EECE9AC-D62E-46C9-A038-69F5B44A22E7',
       '2F4D7A44-E0CA-4CA9-A716-C45DF4CEE753',
       '2F86CB15-8303-42CC-A234-8FB9B9306B68',
       '2F9FBB36-0C3A-47C0-8B4C-A6511B37DB56',
       '2FCB06A6-AA51-4727-B9EE-5D60A9EBE8DC',
       '2FF4AC05-4AC0-49D0-84F4-59726F837224',
       '308C7262-D0B2-4280-8AE9-44AEAD5EDB66',
       '30A92F13-5400-482D-9604-08103317016F',
       '30AD20EF-8233-499F-AD8C-D6159B2A76D5',
       '30D5D8C7-4366-4100-9D00-EFC32FD3A217',
       '30FB9417-75C2-490D-BB77-E94BF9B38D6F',
       '312C1E65-5DC4-474B-9A27-232B566DB552',
       '312F9FE0-824B-4822-BEF2-885CAEBDAD20',
       '3174FC2D-51DB-4B8A-AAC3-17785012D2C8',
       '32178D83-9440-4F99-8E5D-A4B93F18F9AD',
       '332E20D6-58E0-4597-B7E3-BE268FF556D1',
       '34271425-8BE6-4786-B90B-FC628532E848',
       '34302BB3-A02F-49D0-A955-345AAB1F455E',
       '34620492-80D8-4E2A-BFD8-C4A531785229',
       '34766DB2-237F-492F-A5A9-93765DD1F5C5',
       '34B8D323-17FA-4D9C-B74C-7C884850D94F',
       '3560B619-2617-4838-BAF2-B28113BCC536',
       '356F065A-18B8-4E07-A2BD-4B6E7A69C0F1',
       '3581CECD-D877-4726-91C8-D872D1A8B295',
       '3588948D-B9D0-4D01-AA8B-D36212DFB8E6',
       '35F836E2-ED1F-41F1-98C0-684579E56D3D',
       '36411881-49F3-4ADA-B4DC-13298CE93163',
       '365028FC-ADE2-49FA-A17F-A67A9089C54A',
       '366A1650-AC87-42B6-8C52-82BC60538497',
       '36C85FBE-1C29-4529-A82E-B798BD9C1D16',
       '371C16F6-287A-4D70-83A9-063A13EC9605',
       '38027008-BAAE-4704-809E-9FFC56C61594',
       '3807031E-C2DE-4BD7-ABE8-C6D3E9BC55D8',
       '3821984F-A40F-4EF9-AFDA-5066C8649F3D',
       '3827F308-E576-407D-AA94-EA93550CB9F9',
       '3854F70D-8980-4B88-98FA-3D90CDF0D94C',
       '388550B4-7744-4EE5-BE9F-467D874BD87D',
       '38F98756-BBD0-4546-9CA2-CB65C45BBAE1',
       '39541DDF-B302-479A-93CD-477C41D3A489',
       '3996DFE3-6B07-4D94-B5C8-8CCB1AB438B5',
       '39B542D0-AC57-42EC-A1BC-772DA8CF3CBB',
       '3AACCB52-A82C-4DCD-A3A0-9623E13B1A15',
       '3B29D307-DF13-44A5-9D01-4DC2A750B17E',
       '3B3B9377-EE4B-4B61-8A82-80FD22F96964',
       '3B67A4E7-ED22-41BA-A878-3BAB8AB3F555',
       '3B7D82AC-4879-45C1-824F-11639E4B288A',
       '3B9F1D5A-171E-44C6-83F0-CCB16920458B',
       '3BBB16E2-E266-4DB1-8A53-9F069E418A32',
       '3CD2EE7F-1280-4D49-8B29-E2E11D17BDB7',
       '3D05354E-AEFB-474B-B0F6-5FE494A27779',
       '3D7684D9-3257-4F1B-8E79-B97662840B66',
       '3D826EC3-E812-4623-9BE2-401C332931FC',
       '3E4F9969-81C8-4119-B928-26C4E1FE86E1',
       '3E6610B8-8E14-4AA4-B137-1C284D9B7C72',
       '3E7CABA6-9184-4A0E-BD68-F55B84E5B4F5',
       '3EDB60C1-C8CB-412E-AE42-DC21BBF11E33',
       '3EE330AC-37B8-4DB4-AA64-1DD4817FFE78',
       '3F40C1BC-7BC0-4C14-9CFE-F1BFED2B4443',
       '3F5F2B09-8941-4EE6-95ED-0BC5F64068B4',
       '3F6C6A55-D0D8-4E3B-A726-E3DDBCA62004',
       '3F76AF4A-616E-47A1-A294-D87218ECD201',
       '40053BC0-A1BE-477A-97FE-3E8C1D5AF216',
       '4017C3E1-456B-4949-905F-D843810F3DD7',
       '4024F6A7-5FA6-42F4-9338-F631DE0ABD16',
       '404F9D99-7032-4F27-8AEE-4CD7ED0ECB7E',
       '40D16BD9-DB63-415F-8E56-04C90339A533',
       '414BE742-D537-42B0-936E-1BAB383D9131',
       '4164D397-74A1-4086-AE29-705A9DC9DC1B',
       '41741ACC-A10A-407F-AB6E-EB42260C9E93',
       '41B429AB-226D-47D8-9547-408EC68172F5',
       '423D3856-F5C3-4E16-8707-B5FC415EB33E',
       '424F34C2-8AC1-4E00-B7FC-57A6074AC83C',
       '4259C0BE-8683-4893-8BA7-048105187DB5',
       '42C0D141-7EFA-42AC-85C6-8E9498C66BDF',
       '42D182A0-A53F-4D9C-B06A-15A8E1878E75',
       '42F6B546-311E-4790-9651-3E5D24AD09F1',
       '43849629-E0ED-40F9-BD43-226EBBF6EB88',
       '439ECEBA-8ED3-42CE-A155-8CA2DFB9F471',
       '43C62D23-4934-40BE-BD35-6B3E0E5C81BD',
       '43E8EDDC-3451-43FA-92A7-51AFA2E77E8D',
       '440EA036-749C-4345-B9F0-E1794A973548',
       '441FF16E-2C84-4EB2-B56E-622A35135668',
       '44D193CF-0340-4767-8F9A-103B7188F4B9',
       '45442037-992E-4BD5-9B39-C23AFCCBAFC4',
       '454C700B-EE30-4CE6-9CF3-B9093D517BFE',
       '457B50B0-852A-439D-838C-08C48762C496',
       '464A760A-6D2C-4A99-AA20-358D5C5B6EA1',
       '4655934A-B1CC-4F4F-BB13-F2C0604B4A23',
       '46606024-1A87-4E86-BCFD-824294259F33',
       '466F7E2F-96C0-4812-BBED-022503F19CCD',
       '469A2534-A09A-4EE9-9222-EE32D408A36E',
       '47404B6A-9CC1-4592-90F8-5AD906B8C502',
       '4771B1AD-1E1C-4345-9642-A6C84871FF58',
       '477258B7-AEA8-4CB6-8281-7DFF21990449',
       '47752BE6-C0E3-4B78-96A2-EF997ED54BE8',
       '487ED7EE-A2BD-4A8B-9FC9-7DB35BB2C312',
       '48A4D2BB-435C-453B-B081-5D3359B7882E',
       '48D04E22-CEAB-4A83-B3B3-8733BF7B2D50',
       '48F216E2-9AA1-4756-82DF-943558CF33B4',
       '491FF096-02C4-427F-A120-E35295AAA3FC',
       '49308CD6-3B13-4D4D-A157-547BB49F07CF',
       '49D155A8-0680-4AEE-8592-1302620AD066',
       '49FAB090-FB05-4B4A-A17E-926A26BD89FF',
       '4A1D4AFB-0C19-4A3C-BC87-448E3D91E9F1',
       '4AE06524-4E74-4886-8737-A4144471C067',
       '4AEB81FB-B3BC-4D7F-9891-EFEACDC0C2B6',
       '4B3E6370-BBCD-4282-A547-A32C48CE0475',
       '4B4DA773-FAB5-4FE2-B9A8-BDF86BE854F0',
       '4B76F468-57E0-4C82-85C1-84D12074039D',
       '4BB029C6-34DD-46A1-8616-5CE6BD9B7D6B',
       '4BC4B8D1-0205-4C40-9395-0BA316057D46',
       '4C0E5418-F0FA-4858-B862-7819035E3ED2',
       '4C787C6C-653E-4AEB-90D0-C3840CF893F0',
       '4C848C09-DE3A-4998-AC17-81B3DE68028B',
       '4C8E7826-1CAD-4966-B364-0CA62096AFC9',
       '4D877979-7E61-4000-87B6-1DBE9DCF1EC1',
       '4DE5DCA3-EBF1-4A2C-99F6-CE4BD5B91DB2',
       '4DF5B9DB-A18B-45CE-A9D5-72C873C72490',
       '4E6CE82E-8C31-489D-A1E0-1A652FBCEFA9',
       '4E9F794F-95FE-49F7-885B-4A4F2761E70F',
       '4F3E58B8-DDDC-4387-A492-D6D048D11255',
       '4FDB8D78-6C17-4678-AE70-7DDA6083EF03',
       '500DC7A7-1129-483B-B61F-BF8CDFB3AAEA',
       '501E7947-D7C1-48E4-85F0-832B9E3AF4B9',
       '5068D946-1BC0-464B-A52E-31B108CFC07A',
       '5074CD69-B68D-4D68-859C-DB10EBE1ABFC',
       '508185CF-F72A-4918-88D5-7807866ED867',
       '50A0A961-B9F3-4F70-B9AA-D0AA19B07BDA',
       '50B1D944-0655-42E5-B140-F15B2B273A03',
       '50C6D504-2129-48AF-99E5-72729296E2F9',
       '50E139C4-F83E-4289-BCD2-CEE847349899',
       '51AAC8FA-92E4-4824-BC17-9335EE364321',
       '5209CE36-58E1-4E5F-884A-1EC92C6504D2',
       '5210B486-471C-4A50-8344-EE57B01DBAF6',
       '52122412-523A-42BA-BCB3-19BFEDF4903F',
       '5227F7F1-F406-46A4-A6A9-1E462214341E',
       '5275CF58-0435-447E-8E96-3F4A27E2CD4E',
       '52A4287F-22D7-4D81-A57B-E80448ACBA7C',
       '52E430F2-16F2-4FD2-BD46-8F5D8210CF4A',
       '5303C73C-2CB6-48D9-A3B4-8A0DC1A23E9B',
       '535C6E12-5F38-4254-B1C3-0B0198F1BA36',
       '53838877-6EC6-4A4D-AF7C-61F428EA0780',
       '53AFC1EB-27C7-45CC-9356-DD7C69670AC0',
       '53EB7EF8-AB91-410A-A875-5D4C0372B667',
       '54A00E03-6989-48A5-AE20-20FB0FCDAF8E',
       '54C6FEEF-7DC9-43A2-8B1D-74F73FD1CBC4',
       '55114B86-2899-4F53-8CF6-852E1C956070',
       '5520E7B5-EDE4-41E7-89E8-4319EC1A4CB8',
       '55609B8F-E9E0-4617-801D-BC094861E010',
       '5576E876-7D96-4A21-8C86-439BA1F9C2A0',
       '55D54FC9-9CF3-4C27-AD8A-AF12208ED59D',
       '5614E907-FC6F-4D01-8812-E4BAF56FCD25',
       '56CD5362-E5FF-4117-B92A-04F80B4D3C71',
       '56EEC55E-B649-4E8B-A304-B3F745A72DAB',
       '576BFA89-5BF8-44DB-91F5-4B63F11A8126',
       '57FC9A3E-6648-4612-8B29-4863C4749A92',
       '583E5214-D104-4612-A62A-21FEE3CCDAAB',
       '58692347-DEA1-4F46-BB7E-4B79D462DF90',
       '586927D5-DE7F-4EC3-8A07-9658231336B2',
       '590A7001-29E3-4BF4-9425-AA7FFEEA3DE4',
       '59719F81-C861-40D4-9628-0BDB341DF025',
       '598E40E5-1A42-40A9-9882-32A6450E108E',
       '59D818C5-BC82-4AC4-9446-75E1975317F5',
       '5A39A57C-B1C3-4436-AEDD-C9A760715610',
       '5B71EA46-4687-4C1B-B067-B601DF1CAD77',
       '5BF258B8-1233-4378-8E2A-B8CD4E63DB5D',
       '5C1D9FAB-6B94-42DC-B7D1-4B2309F82082',
       '5C56BD9B-BE86-480C-A517-021F2FA11330',
       '5C9910D4-3B13-49F2-8D41-08AFD5E49C10',
       '5D7BE058-F4E3-46C5-A8C5-5CEE6AA12601',
       '5D835043-B750-4434-A94B-26E6D93833BB',
       '5DA0C111-9C77-45DE-94A4-3F8F4AF431A3',
       '5E29825E-5484-43B4-9119-7D0123C883F9',
       '5E432FC1-EE38-4136-9988-C15B0BEC9C50',
       '5F7B7B69-5436-402D-98E1-55EFB231C7B0',
       '5FA46DD2-90E9-46F5-95F4-B993594E2052',
       '5FFBF72F-912B-4265-BBB4-6A699F84D42F',
       '6009A664-BEA4-41B9-AB98-592A6BAD603D',
       '607216F6-1FBB-4329-BEAA-A4FAB7896698',
       '60C0187A-3A7B-4935-B399-4E6BA68E6509',
       '6115DD67-808B-499A-BC85-054018C74DF7',
       '616118A0-36E2-4DF8-BEF1-F7D07D0FE2B4',
       '61FC80EA-36FC-42CE-AAAC-1F7B4EE76885',
       '62649389-7125-4A4B-9295-441E1CF1CD3F',
       '63476F09-4D98-4493-929F-A6D455CB3B6B',
       '636DB189-4B52-4C0D-88E7-447E69F8ABC9',
       '636E66A1-168C-477F-BD53-5683A2C2AF80',
       '63B0F2E0-9E4B-4D4D-93A8-EFDE793E2CD0',
       '63EA87CD-B823-4946-A284-9D1BBB002E9D',
       '64140F09-ED4B-4257-8E1F-E8C602BB770B',
       '64252ED7-77AC-4D44-9BBC-F3E6D118D05B',
       '64483397-01B4-4610-966A-8CFDDD49808C',
       '64923059-A212-432F-8708-B0CA46B8FABB',
       '64BCD756-DF65-4A17-9E2D-6950E5B578BB',
       '64C531B3-A66C-47E3-83B7-2A8DEF4E531F',
       '650A7F20-A172-4BF6-A3C9-0A31701281BC',
       '6522A157-36FE-46F3-A29D-C0AD79302B84',
       '65421C33-72E9-4BB9-9A71-8B80736C8905',
       '65EB7FA3-5552-43FD-8136-E4E5BC97CF1F',
       '66544319-E3B3-4562-A01A-5D773FFA1305',
       '667A26FF-A64B-42D7-9135-7E294625C15F',
       '66F2266D-F4BF-4F98-AB7C-5A4393697634',
       '678BFF3C-4C7C-49D5-B16C-5F6BCEE35730',
       '67E7F699-6F39-459E-9704-30E878CA66D6',
       '67EAAF03-ED48-4BBC-BEE0-6A3E0722A9CD',
       '67EB2BEB-84F3-444B-B54A-CB9A3F2867D6',
       '682DE70F-DD72-4D24-BA7E-E56E40E380FF',
       '68752364-D7A6-43B4-A5B2-FF4602C94195',
       '6939693F-A1DC-4438-8AE0-914669AE0466',
       '6984B6A9-8D0E-4F7F-B980-41D381A63A25',
       '69A71949-AE5E-468B-BD1C-4C64B7217961',
       '6A483764-EC1E-4AD6-A511-E65440F266DB',
       '6A8664E4-4B92-47C6-A803-25492BACDEA8',
       '6A8B1318-89D1-44EE-AB89-88A0056B15DE',
       '6A9EB72B-969E-4E73-B474-36BA403EB2C3',
       '6AC79E44-E194-40D6-B428-54EF3C0E15FE',
       '6AC98795-2FBA-4951-8CDF-BA1210F3B1CF',
       '6B06C922-AB7A-4DEC-8E99-388701C3BEBE',
       '6BAB2A0E-643F-4546-BF2D-0017AC428922',
       '6BB73DE0-103F-44D1-9562-D910BCC0DF3D',
       '6C67C041-4C99-411E-A1F0-4FA9A9D47F61',
       '6C6C1D1F-7087-491A-8AAA-473AAC405A64',
       '6C963E9B-D8F3-4093-9D61-582D7A7F2B38',
       '6CC2FB96-EFF6-4474-80D9-92A44144F644',
       '6D0B4103-A85A-449C-BB88-69EF80C5FF24',
       '6D4D8AAB-07D3-4A1D-BE02-524A055EA1CD',
       '6DCDE433-5899-492E-9412-D84AEA4806DB',
       '6E09A008-5D85-47F0-A4B6-2DAAC19D31DA',
       '6E731CDB-BBDE-46C1-84DC-34411472CCEE',
       '6F362929-E151-4D66-93AC-1BE5F66AAEEE',
       '6F5AC38A-9374-4097-B056-419F546F1FCF',
       '708EC490-51A9-477D-85F3-CF4ED75F9903',
       '70A49280-210D-4AFE-B738-9C3A927B8447',
       '70F8D5EF-B46C-4B39-98A8-38245DC9A3EE',
       '71003985-493A-426D-9F29-3A07FE76ABE2',
       '7123EBAF-1CB7-4494-95D5-24C692029864',
       '72CE8CD7-07C6-42C9-8F65-40EA8B13D901',
       '72DFAB3D-972B-438B-8B68-5F8FFB87A687',
       '7316AEA2-EE2E-4C7F-9DC6-6278E51871D2',
       '73581688-3903-4BD5-9947-FE7AE645CCA3',
       '73E965DC-476C-4F08-9A79-B3D2800D4D8F',
       '73EB8322-F221-4484-AEF6-5151613BEBCC',
       '744EBD6A-ADD8-4EA8-985C-2FE65C1F8FE1',
       '744FBB1D-EC1B-464B-9456-E681A6E07414',
       '745D3E4F-A827-429F-A03B-4B62DA49567D',
       '74BE8981-99AD-49EA-A859-6CA635E6ACA5',
       '74ED19AA-B0CC-42E8-BF40-95EF6D78F878',
       '7503598E-979F-457F-A589-84733C26C150',
       '7593ECAF-F098-4639-8D86-1EDC65D7549A',
       '75AC6EAC-4EB8-42BB-9BC3-AE5330FC4D71',
       '75AFEB7A-673D-44FF-8A6A-3B84925D292D',
       '75E92753-7A53-410A-A378-E42685577620',
       '7675C282-DDD3-4B56-84C6-F8CE936EDE41',
       '7676C48F-F749-424C-B3AE-5148CD8C7EB7',
       '76855C94-D561-4902-99C9-266D6BA5D08C',
       '769C926F-8CB4-433C-A726-E8641C567401',
       '76BF598B-E912-4283-A25D-81CA097E162A',
       '76C599A1-CD43-456F-986C-9B54896749FF',
       '76F19DDF-E9C8-47E9-B742-69555B74B4DD',
       '7785B8BB-AC22-458E-9410-EA2BD4B623D1',
       '77D7D585-6453-4C28-A4B8-4236F1E79AC4',
       '77E7F181-F58D-4E79-AB49-0F8163DCA845',
       '789CBEFF-20A4-4F0C-8937-863A8F5D423C',
       '78A92E76-B364-4755-831B-EE66E9D7B143',
       '79127482-C146-4863-8927-443066648FF6',
       '792BFBA9-91F5-4392-9A2B-922805D7D5B8',
       '79B45C71-0941-463E-B590-DA1C4E643D90',
       '79C20E3C-0E46-4A5B-BE58-5013FF2A2405',
       '7A203341-832E-436A-830D-FF98A7B55949',
       '7A2B9ABE-DF57-4D3E-B8D6-C0D5B9402DA9',
       '7A3189D7-7F61-4F64-B8E4-6BE794E0F05E',
       '7A4448B0-0712-46D6-BB57-18B4BE74C261',
       '7A4C9199-2242-4708-B797-A23631F5289C',
       '7A7E564B-71C8-434B-8463-B665A46A4675',
       '7AC0A618-0DD1-484E-9204-7C581CFFDD37',

In [29]:
from sklearn.preprocessing import LabelEncoder
def features(df):
    df=df.sort_values(['CreditCard_id','MonthEndDate' ],ascending=True)
    features=[ 'CreditCard_id',  'CreditLine',
       'LastStatementBalanceAmount', 'LastStatementPurchaseAmount',
       'LastStatementPurchaseReturnAmount',
       'LastStatementMinimumPaymentDueAmount',
       'LastStatementPaymentTotalAmount',  'DelinquentTotalAmount',
       'LifetimeDelinquent1CycleCount', 'LifetimeDelinquent2CycleCount',
       'LifetimeDelinquent3CycleCount', 'LifetimeDelinquent4CycleCount',
       'LifetimeDelinquent5CycleCount', 'LifetimeDelinquent6CycleCount',
       'LifetimeDelinquent7CycleCount', 'ChargeOffAmount']
    aggr=df[features].groupby("CreditCard_id").agg(['last', 'std', 'min', 'max'])
    aggr.columns = ['_'.join(x) for x in aggr.columns]
    aggr=aggr.reset_index()
    from sklearn.preprocessing import LabelEncoder
    df['CardInternalStatus']= LabelEncoder().fit_transform(df['CardInternalStatus'])
    df['ActivityHistory1_12']= LabelEncoder().fit_transform(df['ActivityHistory1_12'])
    cat=['CreditCard_id', 'CardInternalStatus',
       'ActivityHistory1_12', 'Target']
    aggr_cat=df[cat].groupby("CreditCard_id").agg(['last',lambda x: pd.Series.mode(x)[0]])#lambda x: pd.Series.mode(x)[0]
    aggr_cat.columns = ['_'.join(x) for x in aggr_cat.columns]
    aggr_cat=aggr_cat.reset_index()
    aggr_cat=aggr_cat.drop(columns=['Target_<lambda_0>'])
    aggr_cat.columns=['CreditCard_id', 'CardInternalStatus_last',
       'CardInternalStatus_mode', 'ActivityHistory1_12_last',
       'ActivityHistory1_12_mode', 'Target_last']
    #SSN_id CreditCard_id
    features=['CreditCard_id',  'CreditLine',
       'LastStatementBalanceAmount', 'LastStatementPurchaseAmount',
       'LastStatementPurchaseReturnAmount',
       'LastStatementMinimumPaymentDueAmount',
       'LastStatementPaymentTotalAmount', 'DelinquentTotalAmount',
       'LifetimeDelinquent1CycleCount', 'LifetimeDelinquent2CycleCount',
       'LifetimeDelinquent3CycleCount', 'LifetimeDelinquent4CycleCount',
       'LifetimeDelinquent5CycleCount', 'LifetimeDelinquent6CycleCount',
       'LifetimeDelinquent7CycleCount', 'ChargeOffAmount']
    df_ema=df[features].groupby("CreditCard_id").ewm(span=3).mean()#24
    df_ema=df_ema.reset_index()
    df_ema=df_ema.drop(columns=['level_1'])
    df_ema=df_ema.groupby("CreditCard_id").agg(['last'])
    df_ema.columns = ['_ema_'.join(x) for x in df_ema.columns]
    df_ema=df_ema.reset_index()
    df_merge = pd.merge(aggr, df_ema, how='outer', on=['CreditCard_id'])
    df_merge = pd.merge(df_merge, aggr_cat, how='outer', on=['CreditCard_id'])
    return df_merge

In [30]:
cards=df[df['Target']==1].CreditCard_id.unique()
removed=df_merge[df_merge['Target_last']==1].CreditCard_id.unique()
removed=removed.tolist()
cards=cards.tolist()
for i in removed:
    cards.remove(i)

In [35]:
testi['DelinquentTotalAmount_last']

0    93.0
Name: DelinquentTotalAmount_last, dtype: float64

In [36]:
testi

,CreditCard_id,CreditLine_last,CreditLine_std,CreditLine_min,CreditLine_max,LastStatementBalanceAmount_last,LastStatementBalanceAmount_std,LastStatementBalanceAmount_min,LastStatementBalanceAmount_max,LastStatementPurchaseAmount_last,...,LifetimeDelinquent4CycleCount_ema_last,LifetimeDelinquent5CycleCount_ema_last,LifetimeDelinquent6CycleCount_ema_last,LifetimeDelinquent7CycleCount_ema_last,ChargeOffAmount_ema_last,CardInternalStatus_last,CardInternalStatus_mode,ActivityHistory1_12_last,ActivityHistory1_12_mode,Target_last
0,00F567FC-053D-4AEF-B200-37B0ED41DF1A,3500.0,0.0,3500.0,3500.0,3425.3,169.025596,3171.05,3762.35,0.0,...,0.0,0.0,0.0,0.0,0.0,1,0,6,0,0

In [37]:
reg.predict(testi.drop(columns=['DelinquentTotalAmount_last', 'CreditCard_id', 'Target_last']))

array([0.])

In [38]:
testi['DelinquentTotalAmount_last']

0    93.0
Name: DelinquentTotalAmount_last, dtype: float64

In [40]:
preds1=[]
preds2=[]
for i in cards:
    test1=df[df['CreditCard_id']==i].copy()
    test1=test1.reset_index()
    size=test1[test1['Target']==1].index[0]#+1
    if size==0:
        size+=1
    testi=features(test1.head(size))
    y=testi['DelinquentTotalAmount_last']
    X=testi.drop(columns=['DelinquentTotalAmount_last', 'CreditCard_id', 'Target_last'])
    testi=testi.fillna(0)
    preds1.append(reg.predict(testi.drop(columns=['DelinquentTotalAmount_last', 'CreditCard_id', 'Target_last']))[0])
    preds2.append(y)

In [55]:
[preds1[0]]

[0.0]

In [57]:
rmse=[]
for i in range(0, len(preds1)):
    rmse.append(np.sqrt(mean_squared_error( np.array([preds1[i]]),  np.array(preds2[i]))))

In [59]:
np.mean(rmse)

74.61968824884792

In [109]:
preds1=[]
preds2=[]
for i in cards:
    test1=df[df['CreditCard_id']==i].copy()
    test1=test1.reset_index()
    size=test1[test1['Target']==1].index[0]#+1
    if size==0:
        size+=1
    testi=features(test1.head(size))
    preds1.append(model.predict(testi.iloc[:, 1:-1])[0])
    preds2.append(clf.predict(testi.iloc[:, 1:-1])[0])

In [110]:
from collections import Counter
Counter(preds1)

Counter({1: 653, 0: 215})

In [113]:
653/868

0.7523041474654378

In [97]:
from collections import Counter
Counter(preds1)

Counter({1: 852, 0: 16})

In [99]:
feature_imp = pd.DataFrame(sorted(zip(model.feature_importances_,X.columns)), columns=['Value','Feature'])

In [102]:
feature_imp.tail(20)

    Value                                    Feature
59    980   LastStatementMinimumPaymentDueAmount_std
60    991         LifetimeDelinquent1CycleCount_last
61   1095        LastStatementBalanceAmount_ema_last
62   1172                  DelinquentTotalAmount_max
63   1234       LastStatementPurchaseAmount_ema_last
64   1307        LastStatementPaymentTotalAmount_max
65   1320                  DelinquentTotalAmount_std
66   1329     LifetimeDelinquent2CycleCount_ema_last
67   1519             LastStatementBalanceAmount_max
68   1556            LastStatementBalanceAmount_last
69   1599   LastStatementPaymentTotalAmount_ema_last
70   1919             LastStatementBalanceAmount_min
71   1991             LastStatementBalanceAmount_std
72   2013                   ActivityHistory1_12_last
73   2024     LifetimeDelinquent1CycleCount_ema_last
74   2239          LifetimeDelinquent2CycleCount_std
75   2310                   ActivityHistory1_12_mode
76   2379  LastStatementMinimumPaymentDueAmount_last
77   3100             DelinquentTotalAmount_ema_last
78   3643        LastStatementPaymentTotalAmount_std